<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>安全验证 - 原创专区 - {$kx.config.sitename}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/author/css/style.css"/>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
    <style>
        input[type=text],input[type=password]{
            width: 100%;
            border: 1px solid #d9d9d9;
            background-color: #F5F4F5;
            padding: 10px;
        }
    </style>
</head>
<body>
{include file="/author/system/header"}
<div class="body">
    <div class="bg-white text-center">
        <form action="" method="post">
            <h1 class="color32 size20" style="padding-top: 175px">管理密码</h1>
            <p class="pt20 pb40">尊敬的作者你好，为保护您的著作安全请输入密码核实</p>
            <div style="width: 365px;margin: auto"><input name="password" type="password"></div>
            <button type="submit" class="ptb15 plr45 bg-red color1 border-radius2 block" style="margin: 50px auto 255px;">进入专区</button>
            <a href="#" style="margin-top: 255px" class="color2">忘记密码?</a>
        </form>
    </div>
</div>
{include file="/author/system/footer"}
</body>
</html>