<!doctype html>
<html mip>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="canonical" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" />
	<link rel="stylesheet" type="text/css" href="https://mipcache.bdstatic.com/static/v1/mip.css">
	<style mip-custom>
		blockquote, body, button, caption, dd, div, dl, dt, fieldset, figure, form, h1, h2, h3, h4, h5, h6, hr, html, input, legend, li, menu, ol, p, pre, table, td, textarea, th, ul { margin: 0; padding: 0; box-sizing: border-box; -webkit-user-select: none; -webkit-tap-highlight-color: transparent; outline: 0 }
		address, article, aside, details, figcaption, figure, footer, header, menu, nav, section { display: block }
		table { border-collapse: collapse; border-spacing: 0 }
		caption, th { text-align: left; font-weight: 400 }
		abbr, body, fieldset, html, iframe, img { border: 0 }
		address, cite, dfn, em, i, var { font-style: normal }
		[hidefocus], summary { outline: 0 }
		li { list-style: none }
		h1, h2, h3, h4, h5, h6, small { font-size: 100% }
		sub, sup { font-size: 83% }
		code, kbd, pre, samp { font-family: inherit }
		q:after, q:before { content: none }
		textarea { overflow: auto; resize: none }
		label, summary { cursor: default }
		a, button { cursor: pointer }

		b, em, h1, h2, h3, h4, h5, h6, strong { font-weight: 700 }
		a, a:hover, del, ins, s, u { text-decoration: none }
		body, html { height: 100%; width: 100%; min-width: 20pc }
		body, button, input, keygen, legend, select, textarea { font: 1pc/1.5 "Helvetica Neue",Helvetica,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","微软雅黑",Arial,sans-serif; color: #333; outline: 0; background: #f4f4f4 }
		a, a:hover { color: #333; text-decoration: none }
		.ptm-inline { display: inline-block; vertical-align: top }
		.ptm-block { display: block !important }
		.ptm-show { visibility: visible !important }
		.ptm-hide { display: none !important }
		.ptm-clearfix:after { content: "020"; display: block; height: 0; clear: both; visibility: hidden }
		.ptm-clearfix { clear: both; zoom: 1 }
		.ptm-clear { clear: both }
		.ptm-text-left { text-align: left !important }
		.ptm-text-center { text-align: center !important }
		.ptm-text-right { text-align: right !important }
		.ptm-text-bold { font-weight: 700 !important }
		.ptm-text-cut { white-space: nowrap; text-overflow: ellipsis; overflow: hidden }
		.ptm-line-x { width: 100%; position: relative; height: 1px }
		.ptm-line-x:after { border-bottom: 1px solid #c8c7cc; display: block; content: ''; position: absolute; top: 0; right: 0; bottom: 0; left: 0; -webkit-transform-origin: 0 0; -webkit-transform: scale(1); pointer-events: none }
		.ptm-row-5 { margin-right: -5px; margin-left: -5px }
		.ptm-row-10 { margin-right: -10px; margin-left: -10px }
		.ptm-row-15 { margin-right: -15px; margin-left: -15px }
		.ptm-row-20 { margin-right: -20px; margin-left: -20px }
		.ptm-padded-t0 { padding-top: 0 }
		.ptm-padded-b0 { padding-bottom: 0 }
		.ptm-padded-0-5 { padding: 0 5px }
		.ptm-padded-0-10 { padding: 0 10px }
		.ptm-padded-0-15 { padding: 0 15px }
		.ptm-padded-0-20 { padding: 0 20px }
		.ptm-padded-5 { overflow: hidden; padding: 5px }
		.ptm-padded-10 { overflow: hidden; padding: 10px }
		.ptm-padded-15 { overflow: hidden; padding: 15px }
		.ptm-padded-20 { overflow: hidden; padding: 20px }
		.ptm-text-default { color: #666 !important }
		.ptm-text-primary { color: #1abc9c !important }
		.ptm-text-success { color: #2ecc71 !important }
		.ptm-text-info { color: #3498db !important }
		.ptm-text-warning { color: #f82 !important }
		.ptm-text-danger { color: #e74c3c !important }
		.ptm-text-blue { color: #a1d4cf !important }
		.ptm-text-pink { color: #fbb8af !important }
		.ptm-text-orange { color: orange !important }
		.ptm-text-write { color: #fff !important;z-index:10;position: relative }
		.ptm-bg-white { background-color: #fff !important }
		.ptm-pull-right { float: right !important }
		.ptm-pull-left { float: left !important }
		.ptm-content { -webkit-overflow-scrolling: touch }
		.ptm-content-title { position: relative; overflow: hidden; margin: 0; white-space: nowrap; text-overflow: ellipsis; font-size: 14px; text-transform: uppercase; line-height: 1; color: #6d6d72; padding: 25px 15px 10px }
		.ptm-content-padded { -webkit-overflow-scrolling: touch }
		.ptm-card, .ptm-content-padded { margin: 0 10px; margin-bottom: 15px }
		.ptm-card { position: relative; background: #fff; border-radius: 6px }
		.ptm-card:after { display: block; content: ''; position: absolute; top: 0; right: 0; bottom: 0; left: 0; -webkit-transform-origin: 0 0; -webkit-transform: scale(1); pointer-events: none; border: 1px solid #c8c7cc; border-radius: 6px; overflow: hidden }
		.ptm-card.ptm-noborder:after { border: 0; overflow: hidden }
		.ptm-card.ptm-noborder .ptm-list-view, .ptm-card.ptm-noborder .ptm-user-view { border-radius: 6px }
		.ptm-card .ptm-form { background: 0 }
		.ptm-card .ptm-input-row:first-child:after, .ptm-card .ptm-list-view-cell:first-child:after, .ptm-card .ptm-user-view-cell:first-child:after, .ptm-content-padded .ptm-list-view-cell:first-child:after, .ptm-content-padded .ptm-user-view-cell:first-child:after { border-top: 0 }
		.ptm-card .ptm-btn-row:after, .ptm-card .ptm-input-row:last-child:after, .ptm-card .ptm-list-view-cell:last-child:after, .ptm-card .ptm-user-view-cell:last-child:after, .ptm-content-padded .ptm-list-view-cell:last-child:after, .ptm-content-padded .ptm-user-view-cell:last-child:after { border-bottom: 0 }
		.ptm-card .ptm-card-header { height: 40px; line-height: 40px; font-size: 1pc; border-bottom: 1px solid #eee; padding: 0 10px }
		.ptm-card .ptm-card-content { padding: 10px }
		.ptm-card .ptm-card-footer { height: 40px; line-height: 40px; border-top: 1px solid #eee; font-size: 1pc; text-align: center }
		.ptm-card .ptm-card-footer a { display: block; width: 100%; height: 100% }
		.ptm-card .ptm-card-more { padding: 10px }
		.ptm-card .ptm-card-more .loadmore { background: #1abc9c; color: #fff; -webkit-border-radius: 1px; border: 0; display: block; font-size: 1pc; height: 36px; letter-spacing: 1px; line-height: 36px; text-align: center }
		.ptm-btn, button { position: relative; display: inline-block; padding: 6px 9pt; margin-bottom: 0; font-size: 14px; font-weight: 400; line-height: 1.42857143; text-align: center; background-color: #ddd; white-space: nowrap; vertical-align: middle; -ms-touch-action: manipulation; touch-action: manipulation; cursor: pointer; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; border: 1px solid #ddd; border-radius: 4px }
		.ptm-btn-default, .ptm-btn:active { color: #fff; background-color: #bdc3c7 }
		.ptm-btn-default { border: 1px solid #bdc3c7 }
		.ptm-btn-primary { color: #fff; background-color: #1abc9c; border: 1px solid #1abc9c }
		.ptm-btn-primary.active, .ptm-btn-primary:active { color: #fff; background-color: #16a085; border: 1px solid #16a085 }
		.ptm-btn-success { color: #fff; background-color: #2ecc71; border: 1px solid #2ecc71 }
		.ptm-btn-success.active, .ptm-btn-success:active { color: #fff; background-color: #27ae60; border: 1px solid #27ae60 }
		.ptm-btn-info { color: #fff; background-color: #3498db; border: 1px solid #3498db }
		.ptm-btn-info.active, .ptm-btn-info:active { color: #fff; background-color: #2980b9; border: 1px solid #2980b9 }
		.ptm-btn-warning { color: #fff; background-color: #f82; border: 1px solid #f82 }
		.ptm-btn-warning.active, .ptm-btn-warning:active { color: #fff; background-color: #faa732; border: 1px solid #faa732 }
		.ptm-btn-danger { color: #fff; background-color: #e74c3c; border: 1px solid #e74c3c }
		.ptm-btn-danger.active, .ptm-btn-danger:active { color: #fff; background-color: #c0392b; border: 1px solid #c0392b }
		.ptm-btn-block { display: block; width: 100%; padding: 15px 0; margin-bottom: 0; font-size: 18px }
		.ptm-btn .ptm-iconfont, .ptm-btn-block .ptm-iconfont { margin-right: 6px }
		.ptm-btn .ptm-badge, .ptm-btn-block .ptm-badge { margin-left: 6px }
		.ptm-btn-outlined { background: 0 0 }
		.ptm-btn-default.ptm-btn-outlined { color: #bdc3c7 }
		.ptm-btn-primary.ptm-btn-outlined { color: #16a085 }
		.ptm-btn-success.ptm-btn-outlined { color: #27ae60 }
		.ptm-btn-info.ptm-btn-outlined { color: #2980b9 }
		.ptm-btn-warning.ptm-btn-outlined { color: #faa732 }
		.ptm-btn-danger.ptm-btn-outlined { color: #c0392b }
		.ptm-btn-default.ptm-btn-outlined:active { background: #bdc3c7; color: #fff }
		.ptm-btn-primary.ptm-btn-outlined:active { background: #16a085; color: #fff }
		.ptm-btn-success.ptm-btn-outlined:active { background: #27ae60; color: #fff }
		.ptm-btn-info.ptm-btn-outlined:active { background: #2980b9; color: #fff }
		.ptm-btn-warning.ptm-btn-outlined:active { background: #faa732; color: #fff }
		.ptm-btn-danger.ptm-btn-outlined:active { background: #c0392b; color: #fff }
		input[type=color], input[type=date], input[type=datetime-local], input[type=datetime], input[type=email], input[type=month], input[type=number], input[type=password], input[type=search], input[type=tel], input[type=text], input[type=time], input[type=url], input[type=week], select, textarea { width: 100%; -webkit-appearance: none; padding: 10px 15px; margin-bottom: 15px; line-height: 21px; -webkit-user-select: text; background-color: #fff; border: 1px solid rgba(0, 0, 0, .2); border-radius: 3px; outline: 0 }
		.ptm-form { position: relative; background: #fff }
		.ptm-input-row { position: relative; display: table; padding: 6px 0 }
		.ptm-input-row:after { border-bottom: 1px solid #c8c7cc }
		.ptm-input-row:after, .ptm-input-row:first-child:after { display: block; content: ''; position: absolute; top: 0; right: 0; bottom: 0; left: 0; -webkit-transform-origin: 0 0; -webkit-transform: scale(1); pointer-events: none }
		.ptm-input-row:first-child:after { border-top: 1px solid #c8c7cc }
		.ptm-input-row:last-child:after { border-bottom: 1px solid #c8c7cc }
		.ptm-input-row .ptm-input-addon { font-size: 14px; font-weight: 400; line-height: 1; color: #333; text-align: center; display: table-cell; width: 1%; white-space: nowrap; vertical-align: middle; padding: 5px }
		.ptm-input-row .ptm-input { font-size: 14px; margin: 0; display: table-cell; position: relative; float: left; width: 100%; border: 0; border-radius: 0 }
		.ptm-btn-row { position: relative; text-align: center; padding: 15px }
		.ptm-btn-row:after { border-bottom: 1px solid #c8c7cc; display: block; content: ''; position: absolute; top: 0; right: 0; bottom: 0; left: 0; -webkit-transform-origin: 0 0; -webkit-transform: scale(1); pointer-events: none }
		.ptm-content > .ptm-list-view:last-child { margin-bottom: 15px }
		.ptm-list-view { position: relative; padding-left: 0; margin-top: 0; list-style: none; background-color: #fff }
		.ptm-list-view-cell { position: relative; padding: 5px 8px; overflow: hidden; -webkit-transform-style: preserve-3d; transform-style: preserve-3d; -webkit-touch-callout: none;font-size:13px; }
		.ptm-list-view-cell:after { border-bottom: 1px solid #c8c7cc }
		.ptm-list-view-cell:after, .ptm-list-view-cell:first-child:after { display: block; content: ''; position: absolute; top: 0; right: 0; bottom: 0; left: 0; -webkit-transform-origin: 0 0; -webkit-transform: scale(1); pointer-events: none }
		.ptm-list-view-cell:first-child:after { border-top: 1px solid #c8c7cc }
		.ptm-list-view-cell:last-child:after { border-bottom: 1px solid #c8c7cc }
		.ptm-list-view-cell > a { position: relative; padding: inherit; margin: -9pt -15px; display: block; overflow: hidden; color: inherit; text-overflow: ellipsis; white-space: nowrap }
		.ptm-list-view-cell > a:active { background: #f4f4f4 }
		.ptm-list-view-cell > a.ptm-active { background-color: #eee }
		.ptm-list-view-cell > a.ptm-ellipsis-1, .ptm-list-view-cell > a.ptm-ellipsis-2 { padding-right: 30px }
		.ptm-list-view-cell p { margin-bottom: 0 }
		.ptm-list-view-cell > .ptm-badge, .ptm-list-view-cell > a > .ptm-badge { position: absolute; top: 50%; right: 15px; -webkit-transform: translateY(-50%); transform: translateY(-50%) }
		.ptm-list-view-cell > a.ptm-arrow-right > .ptm-badge { right: 30px }
		.ptm-arrow-right:after, .ptm-list-view-cell > a.ptm-arrow-right > .ptm-badge { position: absolute; top: 50%; -webkit-transform: translateY(-50%); transform: translateY(-50%) }
		.ptm-arrow-right:after { font-size: inherit; line-height: 1; color: #bbb; text-decoration: none; display: inline-block; -webkit-font-smoothing: antialiased; }
		.ptm-list-view .ptm-img, .ptm-list-view .ptm-img-body { overflow: hidden }
		.ptm-list-view .ptm-img-object { max-width: 60px; height: 60px; line-height: 60px }
		.ptm-list-view .ptm-img-object.ptm-pull-left { margin-right: 15px }
		.ptm-list-view .ptm-img-object.ptm-pull-right { margin-left: 0 }
		.ptm-list-view.ptm-grid-view { display: table; width: 100%; padding: 0 10px 10px 0; font-size: 0; white-space: normal }
		.ptm-list-view.ptm-grid-view .ptm-list-view-cell { display: table-cell; padding: 10px 0 0 10px; text-align: center; vertical-align: middle; background: 0 }
		.ptm-list-view.ptm-grid-view .ptm-list-view-cell:after { border-bottom: 0 }
		.ptm-list-view.ptm-grid-view .ptm-list-view-cell .ptm-img-object { width: 100%; max-width: 100%; height: auto }
		.ptm-list-view.ptm-grid-view .ptm-list-view-cell .ptm-img-body { font-size: 14px; padding: 5px 0 }
		.ptm-list-view.ptm-grid-view .ptm-list-view-cell:active, .ptm-list-view.ptm-grid-view .ptm-list-view-cell > a:active { background: 0 }
		.ptm-list-view.ptm-grid-view .ptm-list-view-cell .ptm-media-body { display: table-cell; width: 100%; height: 15px; margin-top: 8px; font-size: 15px; line-height: 15px; color: #333; text-overflow: ellipsis }
		.ptm-list-view.ptm-grid-view .ptm-list-view-cell:after, .ptm-list-view.ptm-grid-view .ptm-list-view-cell:before { border-top: 0 }
		.ptm-thumb-view { overflow: hidden; padding: 10px 8px 5px }
		.ptm-thumb-view .ptm-list-view-cell { display: table-cell; padding: 0 2px 4px; margin-right: 0; margin-bottom: -4px; font-size: 17px; text-align: center; vertical-align: middle; background: 0 }
		.ptm-thumb-view .ptm-list-view-cell .ptm-img-object { width: 100%; max-width: 100%; height: auto }
		.ptm-thumb-view .ptm-list-view-cell > a { margin: 0 0 0 -8px }
		.ptm-thumb-view .ptm-list-view-cell:active, .ptm-thumb-view .ptm-list-view-cell > a:active { background: 0 }
		.ptm-thumb-view .ptm-list-view-cell:after, .ptm-thumb-view .ptm-list-view-cell:before { border-top: 0 }
		.ptm-bar { position: relative; top: 0; left: 0; z-index: 10; width: 100%; background-color: #1abc9c; color: #fff; display: block; height: 45px; line-height: 45px; font-size: 18px; text-align: center }
		.ptm-title { position: absolute; width: 100%; margin: 0 -10px; text-align: center; white-space: nowrap;z-index:1; }
		.ptm-title a { color: inherit }
		.ptm-nav { position: fixed; right: 0; left: 0; bottom: 0; z-index: 10 }
		.ptm-nav, .ptm-nav .ptm-bar-tab { width: 100%; height: 55px; background-color: #fff }
		.ptm-nav .ptm-bar-tab { display: -webkit-box; box-sizing: border-box; font-size: 9pt }
		.ptm-nav .ptm-bar-tab li { position: relative; text-align: center; color: #666; width: 100%; box-flex: 1; -webkit-box-flex: 1; box-sizing: border-box }
		.ptm-nav .ptm-bar-tab p { font-size: 9pt; margin-bottom: 0 }
		.ptm-nav .ptm-bar-tab .ptm-iconfont { font-size: 22px; color: #8f8f94; padding-top: 5px; height: 30px; line-height: 30px; display: inline-block }
		.ptm-nav .ptm-bar-tab .active .ptm-iconfont, .ptm-nav .ptm-bar-tab .active p { color: #16a085 }
		.ptm-nav .ptm-bar-tab .active-dark .ptm-iconfont, .ptm-nav .ptm-bar-tab .active-dark p { color: #34495e }
		.ptm-nav .ptm-bar-tab .active-primary .ptm-iconfont, .ptm-nav .ptm-bar-tab .active-primary p { color: #1abc9c }
		.ptm-nav .ptm-bar-tab .active-info .ptm-iconfont, .ptm-nav .ptm-bar-tab .active-info p { color: #2980b9 }
		.ptm-nav .ptm-bar-tab .active-danger .ptm-iconfont, .ptm-nav .ptm-bar-tab .active-danger p { color: #c0392b }
		.ptm-nav .ptm-bar-tab .active-success .ptm-iconfont, .ptm-nav .ptm-bar-tab .active-success p { color: #27ae60 }
		.ptm-nav .ptm-bar-tab .active-warning .ptm-iconfont, .ptm-nav .ptm-bar-tab .active-warning p { color: #faa732 }
		.ptm-tab, .ptm-tab-nav { width: 100%; overflow: hidden }
		.ptm-tab-nav { display: -webkit-box; font-size: 1pc; height: 45px; box-sizing: border-box; background-color: #fff }
		.ptm-tab-sm .ptm-tab-nav { height: 35px; font-size: 14px }
		.ptm-tab-nav li { height: 45px; line-height: 45px; min-width: 60px; box-flex: 1; -webkit-box-flex: 1; text-align: center; color: #666; box-sizing: border-box; border-bottom: 2px solid transparent; width: 100% }
		.ptm-tab-nav li a { display: block }
		.ptm-tab-sm .ptm-tab-nav li { height: 35px; line-height: 35px }
		.ptm-tab-nav li.active { color: #1abc9c; border-bottom: 2px solid #1abc9c; -webkit-animation: fadeIn .5s ease both; animation: fadeIn .5s ease both }
		.ptm-tab-nav.ptm-tab-border { background-color: transparent; border: 1px solid #1abc9c; border-radius: 3px }
		.ptm-tab-nav.ptm-tab-border li { width: 1%; overflow: hidden; line-height: 43px; color: #1abc9c; background-color: #fff; border-color: #1abc9c; border-left: 1px solid #1abc9c }
		.ptm-tab-sm .ptm-tab-nav.ptm-tab-border li { line-height: 33px }
		.ptm-tab-nav.ptm-tab-border li:first-child { border-left: 0 solid #1abc9c }
		.ptm-tab-nav.ptm-tab-border li.active { background-color: #1abc9c; color: #fff; -webkit-animation: fadeIn .5s ease both; animation: fadeIn .5s ease both }
		.ptm-tab-content-item { display: none }
		.ptm-tab-content-item.active { display: block }
		.footer { padding: 0 10px 20px; margin-top: 10px; text-align: center }
		.footer p { font-size: 9pt; color: #aaa; line-height: 2em }
		.footer a { font-size: 14px; display: inline-block; color: #666; padding: 0 10px }
		.pt-name, .pt-name a { font-size: 15px !important }
		.pt-author, .pt-author a { font-size: 14px }
		.pt-info, .pt-info a { font-size: 13px }
		.pt-desc, .pt-desc a { font-size: 9pt; color: #999 }
		.pt-num { font-size: 13px; line-height: 1pc }
		.pt-cover img { width: 100%; height: 100%; display: block }
		.pt-card { line-height: 1 }
		.pt-card li { display: -webkit-box; padding-bottom: 10px; border-bottom: 1px dashed #eee; margin-bottom: 10px }
		.pt-card li:last-child { margin-bottom: 0; padding-bottom: 0; border-bottom: 0 }
		.pt-card .pt-novel { -webkit-box-flex: 1; position: relative }
		.pt-card .pt-icon { margin-right: 10px; font-size: 9pt; width: 21px; line-height: 21px; position: relative }
		.pt-card .pt-icon i { width: 100%; height: 21px; text-align: center; background: #eee; position: absolute; left: 0; top: 50%; -webkit-transform: translateY(-50%) }
		.pt-card .pt-icon i.start { background: #1abc9c; color: #fff }
		.pt-card-1 .pt-author { color: #777 }
		.pt-card-2 .pt-cover { width: 60px; height: 5pc; margin-right: 10px }
		.pt-card-2 .pt-name { margin-bottom: 8px }
		.pt-card-2 .pt-info { margin-bottom: 5px; color: #666 }
		.pt-card-2 .pt-desc { line-height: 1.8; color: #999 }
		.pt-card-3 .pt-cover { width: 60px; height: 5pc; margin-right: 10px }
		.pt-card-3 .pt-name { margin-bottom: 5px }
		.pt-card-3 .pt-info, .pt-card-3 .pt-info a { color: #999 }
		.pt-card-3 .pt-author, .pt-card-3 .pt-author a { color: #999; margin-bottom: 8px }
		.pt-card-3 .pt-desc, .pt-card-3 .pt-desc a { line-height: 20px; margin-bottom: 5px; color: #999 }
		.pt-card-4 .pt-cover { width: 30px; height: 36px; margin-right: 10px }
		.pt-card-4 .pt-name { margin-bottom: 8px }
		.pt-card-4 .pt-info, .pt-card-4 .pt-info a { font-size: 9pt; color: #666 }
		.pt-card-4 .pt-desc, .pt-card-4 .pt-desc a { font-size: 9pt; color: #999 }
		.pt-card-5 .pt-name { margin-bottom: 8px }
		.pt-card-5 .pt-author, .pt-card-5 .pt-author a, .pt-card-5 .pt-desc, .pt-card-5 .pt-desc a { color: #666 }
		.pt-card-6 .pt-one { margin-bottom: 8px }
		.pt-card-6 .pt-author, .pt-card-6 .pt-author a { color: #666 }
		.pt-card-7 .pt-cover { width: 45px; height: 60px; margin-right: 8px }
		.pt-card-7 .pt-name { margin-bottom: 8px }
		.pt-card-7 .pt-info, .pt-card-7 .pt-info a { color: #999 }
		.pt-card-7 .pt-author, .pt-card-7 .pt-author a { color: #999; margin-bottom: 8px }
		.pt-card-7 .pt-desc { color: #999 }
		.ptm-srot .ptm-desc { font-size: 14px; color: #666 }
		.pt-infopage { padding: 10px }
		.pt-infopage .baseinfo { display: -webkit-box; line-height: 1 }
		.pt-infopage .baseinfo .cover { width: 90px; height: 90pt; margin-right: 15px }
		.pt-infopage .baseinfo .pt-novel { height: 90pt; overflow: hidden }
		.pt-infopage .baseinfo .pt-name { font-size: 17px !important; margin-bottom: 13px }
		.pt-infopage .baseinfo .pt-info { font-size: 15px !important; margin-bottom: 10px }
		.pt-infopage .baseinfo .pt-info:last-child { margin-bottom: 0 }
		.pt-infopage .twobutton > div { padding: 10px }
		.pt-infopage .twobutton .ptm-btn-block { font-size: 14px; padding: 5px 0 }
		.pt-infopage .intro { margin-top: 10px; display: -webkit-box; overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical;  font-size: 14px; color: #666; line-height: 1.8 }
		.pt-infopage .lastchapter { height: 30px; line-height: 30px; display: -webkit-box; margin-bottom: 5px }
		.pt-infopage .lastchapter a { display: block; -webkit-box-flex: 1; font-size: 14px; margin-right: 10px; width: 100% }
		.pt-infopage .lastchapter span { width: 50px; color: #999; font-size: 13px }
		.pt-dir { padding: 0 10px !important }
		.pt-dir .ptm-list-view-cell > a { line-height: 35px; font-size: 14px }
		.pt-dir .ptm-list-view-cell > span { font-size: 14px; color: #999; position: absolute; right: 15px; top: 0; line-height: 35px }
		.pt-dir .ptm-arrow-right:after { right: 0 }
		.pt-card-1 .pt-name, .pt-infopage-more .ptm-card-footer, .pt-infopage-more .ptm-card-header { font-size: 15px !important }
		.pt-dir-page .ptm-btn-block { font-size: 14px; line-height: 20px; padding: 5px 0; margin-top: 9px }
		.pt-dir-page .ptm-btn { background: #fff }
		.pt-dir-list .ptm-card-footer, .pt-dir-list .ptm-card-header { height: 50px; padding: 0 10px }
		.pt-dir-list .pt-dir-icon { position: absolute; right: 10px; line-height: 20px }
		.pt-dir-sel { position: fixed; top: 50%; left: 10%; z-index: 200; width: 80%; padding: 15px 15px 0; background-color: #fff; -webkit-transform: translateY(-50%); border-radius: 4px; text-align: center; box-sizing: border-box; -webkit-box-sizing: border-box; background-repeat: repeat-x; background-size: 100% 1px; background-position: left bottom; background-image: -webkit-gradient(linear, left top, left bottom, color-stop(.5, transparent), color-stop(.5, #e6e6e6)) }
		.pt-dir-sel .title { font-size: 1pc }
		.pt-dir-sel ul { margin-top: 15px; height: 308px; overflow-y: scroll }
		.pt-dir-sel ul li { height: 44px; line-height: 44px; text-align: left; font-size: 14px; color: #333; position: relative; background-repeat: repeat-x; background-size: 100% 1px; background-position: left bottom; background-image: -webkit-gradient(linear, left top, left bottom, color-stop(.5, transparent), color-stop(.5, #e6e6e6)) }
		.pt-dir-sel ul li a { display: inline-block; width: 100%; height: 100% }
		.pt-dir-sel ul li.active, .pt-dir-sel ul li.active a { color: #1abc9c }
		.pt-dir-sel ul li.active:after { position: absolute; right: 0; top: 0; display: block; width: 22px; height: 44px; font-family: ptmicon !important; content: '\e645' }
		.ptm-card-header .ptm-pull-right { font-size: 14px }
		.imgarea { width: 100%; height: 0; padding-bottom: 125%; overflow: hidden }
		.ptm-left-10 { padding-left: 10px; }
		.ptm-right-10 { padding-right: 10px; }
		.pt-infopage-more{margin-top:15px;}
		.ptm-col-xs-6{width:48%;float:left}
	</style>
</head>
<body>
<mip-cambrian site-id="{$kx.config.xiongzhang.appid}"></mip-cambrian>
<header class="ptm-bar ptm-bar-nav  ptm-fix">
	<a class="ptm-pull-left ptm-text-write ptm-left-10" href="{=$kx.config.mobileurl?:$kx.config.siteurl}" target="_blank">首页</a>
	<div class="ptm-title">
		<a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" title="{$novel.name}" target="_blank">{$novel.name}</a>
	</div>
	<a class="ptm-pull-right ptm-text-write ptm-right-10" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.rank.index}" target="_blank">排行</a>
</header>
<section class="ptm-content pt-infopage ptm-bg-white">
	<div class="baseinfo">
		<div class="pt-cover">
			<mip-img src="{$kx.config.coverurl}{$novel.cover}" title="{$novel.name}" alt="{$novel.name}" class="cover" popup></mip-img>
		</div>
		<div class="pt-novel">
			<h1 class="pt-name">
				<a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" title="{$novel.name}" target="_blank">{$novel.name}</a>
			</h1>
			<div class="pt-info">作者:
				<a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=author.space.index authorid=$author.id pinyin=$author.pinyin name=$author.name}" title="{$author.name}" target="_blank">{$author.name}</a>
			</div>
			<div class="pt-info">分类:
				<a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.category.list categoryid=$category.id key=$category.key}" title="{$category.name}" target="_blank">{$category.name}</a>
			</div>
			<div class="pt-info">来源: {$source.name}</div>
			<div class="pt-info">更新: {$last.time|cntime}</div>
		</div>
	</div>
	<div class="twobutton ptm-clearfix">
        <div class="ptm-col-xs-6">
            {if $ismark}
            <a class="ptm-btn ptm-btn-warning ptm-btn-block" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=user.mark.del novelid=$novel.id}" rel="nofollow" target="_blank">移出书架</a>
            {else}
            <a class="ptm-btn ptm-btn-warning ptm-btn-block" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=user.mark.add novelid=$novel.id}" rel="nofollow" target="_blank">加入书架</a>
            {/if}
        </div>
        <div class="ptm-col-xs-6">
            <a class="ptm-btn ptm-btn-primary ptm-btn-block" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.chapter.read novelid=$novel.id pinyin=$novel.pinyin chapterid=1}" target="_blank">开始阅读</a>
        </div>
	</div>
	<div class="ptm-line-x"></div>
	{if $novel.intro}
	<div class="intro">
		{$novel.intro|showintro}
	</div>
	{/if}
</section>
<section class="pt-infopage-more">
	<div class="ptm-card ">
		<div class="ptm-card-header">
			{$novel.name}最近章节
		</div>
		<div class="ptm-card-content pt-dir">
			<ul class="ptm-list-view">
                {block method=chapter.list novelid=$novel.id num=5 name=$list sort=desc}
                {loop}
                <li class="ptm-list-view-cell">
                    <a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.chapter.read novelid=$novel.id pinyin=$novel.pinyin chapterid=$loop.chapterid}" title="{$novel.name} {$loop.name}" target="_blank">{$loop.name}</a>
                </li>
                {/loop}
			</ul>
        </div>
        <div class="ptm-card-footer">
            {if $kx.config.mobileurl}
            <a href="{$kx.config.mobileurl}{link=novel.novel.dir novelid=$novel.id pinyin=$novel.pinyin}" target="_blank">查看目录></a>
            {else}
            <a href="{$kx.config.siteurl}{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" target="_blank">查看目录></a>
            {/if}
		</div>
	</div>
    {block method="novel.list" name=list author=$author.id num=6 order='postdate'}
	{if $list }
	<div class="ptm-card mt10">
		<div class="ptm-card-header ptm-clearfix">
			{$author.name}作品大全
		</div>
		<div class="ptm-card-content">
			<ul class="pt-card pt-card-3">
				{section loop=$list}
				<li>
					<div class="pt-cover">
						<a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" target="_blank">
							<mip-img src="{$kx.config.coverurl}{$loop.novel.cover}" alt="{$loop.novel.name}"></mip-img>
						</a>
					</div>
					<div class="pt-novel">
						<div class="pt-num ptm-pull-right"><span class="orange">{$loop.data.mark}</span>人关注</div>
                        <div class="pt-name">
                            <a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" target="_blank">{$loop.novel.name}</a>
                        </div>
                        <div class="pt-author">
                            <a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}" title="{$loop.author.name}" target="_blank">{$loop.author.name}</a>
                            |
                            <a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.category.list categoryid=$loop.category.id key=$loop.category.key}" title="{$loop.category.name}" target="_blank">{$loop.category.name}</a>
                            | {$loop.novel.is_over|default="连载中","已完结"}
                        </div>
                        <div class="pt-author ptm-text-cut">
                            <a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.last.name}" target="_blank">{$loop.last.name}</a>
                        </div>
                        <div class="pt-info">{$loop.last.time|cntime}更新</div>
					</div>
				</li>
				{/loop}
			</ul>
		</div>
	</div>
	{/if}
    <div class="ptm-card mt15">
        <div class="ptm-card-header ptm-clearfix">
            <div class="ptm-pull-left">
                热门推荐
            </div>
        </div>
        <div class="ptm-card-content pd0">
            <ul class="pt-card pt-card-7">
                {block method="novel.list" name=list order=weekvisit sort=desc num=3}
                {loop=$list}
                <li>
                    <div class="pt-cover">
                        <a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" target="_blank">
                            <mip-img src="{$kx.config.coverurl}{$loop.novel.cover}" alt="{$loop.novel.name}" layout="responsive" width="45" height="60"></mip-img>
                        </a>
                    </div>
                    <div class="pt-novel">
                        <div class="pt-name"><a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" target="_blank" title="{$loop.novel.name}">{$loop.novel.name}</a></div>
                        <div class="pt-author"><a href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}" target="_blank" title="{$loop.author.name}">{$loop.author.name}</a></div>
                        <div class="pt-desc ptm-text-cut">{$loop.novel.intro}</div>
                    </div>
                </li>
                {/loop}
            </ul>
        </div>
    </div>
</section>
<div class="ptm-line-x"></div>
<div class="footer">
	<p>本站系基于互联网搜索引擎技术为您提供信息检索服务。</p>
	<p>
        <a title="隐私声明" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=page.detail key=privacy}" class="color4">隐私声明</a>
        <a title="免责声明" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=page.detail key=disdaimer}" class="color4">免责声明</a>
        <a title="关于我们" href="{=$kx.config.mobileurl?:$kx.config.siteurl}{link=page.detail key=about}" class="color4">关于我们</a>
	</p>
	<p>Copyright ©2019 </p>
</div>

<script src="https://c.mipcdn.com/static/v1/mip-stats-baidu/mip-stats-baidu.js"></script>
<script src="https://c.mipcdn.com/static/v1/mip.js"></script>
<script src="https://c.mipcdn.com/extensions/platform/v1/mip-cambrian/mip-cambrian.js"></script>
<mip-stats-baidu>
<script type="application/json">
	{
		"token": "{$kx.config.tongji.mip}",
		"_setCustomVar": [2, "page", "mip", 3],
		"_setAutoPageview": [true]
	}
</script>
</mip-stats-baidu>
<script type="application/ld+json">
    {
        "@context": "https://ziyuan.baidu.com/contexts/cambrian.jsonld",
        "@id": "{$kx.config.mipurl}{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}",
        "appid": "{$kx.config.xiongzhang.appid}",
        "title": "{$tkd.title|parseTpl}",
        "images": ["{$novel.cover}"],
        "description": "{$novel.intro|showIntroLine}",
        "pubDate": "{$novel.postdate|date="Y-m-d\TH:i:s"}",
        "upDate": "{$last.time|date="Y-m-d\TH:i:s"}"
    }
</script>
</body>
</html>
