<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/style.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<!-- 头部 -->
{include file="/system/header"}
<!-- 内容 -->
<div class="pt-content mt10">
    <!-- 一楼 -->
    <div class="pt-floor1">
        <div class="fl">
            <!-- 排名 -->
            {block method="pagination" name="paginate" page=$page limit=$pagesize count=$count maxpage=50 section=3}
            <div class="relative pt-rank">
                <div class="pt-rank-head">
                    <span class="size18 color2 mr10">全本小说列表</span>
                </div>
                <!-- 选择分类 -->
                <div class="pt-sort-detail">
                    <div class="color7 border-e9 pt-sortdetail-title">
                        <span class="fl pt-sortdetail-item1">类别</span>
                        <span class="fl pt-sortdetail-item2">书名</span>
                        <span class="fl pt-sortdetail-item3">最新章节</span>
                        <span class="fl pt-sortdetail-item4">作者</span>
                        <span class="fl pt-sortdetail-item5">更新时间</span>
                    </div>
                    {block method="novel.list" name=list order=lastupdate num=$paginate.limit page=$paginate.current isover=1}
                    {section loop=$list item=$loop}
                    <div class="color7 pt-sortdetail-title">
                        <span class="fl compulsory-row-one pt-sortdetail-item1"><a title="{$loop.category.name}" href="{link=novel.category.list id=$loop.category.id key=$loop.category.key}">{$loop.category.name}</a></span>
                        <span class="fl compulsory-row-one pt-sortdetail-item2"><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}">{$loop.novel.name}</a></span>
                        <span class="fl compulsory-row-one pt-sortdetail-item3">{if $loop.last.id}<a title="{$loop.last.name}" href="{link=novel.chapter.read novelid=$loop.novel.id pinyin=$loop.novel.pinyin chapterid=$loop.last.id}">{$loop.last.name}</a>{else}{$loop.last.name}{/if}</span>
                        <span class="fl compulsory-row-one pt-sortdetail-item4" title=">{$loop.author.name}"><a title="{$loop.author.name}" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a></span>
                        <span class="fl compulsory-row-one pt-sortdetail-item5">{$loop.last.time|date="m-d H:i"}</span>
                    </div>
                    {/section}
                </div>
                <!-- 分页 -->
                {if $paginate.total>1}
                <div class="pt-pages">
                    <div class="pt30 color5">
                        {if $paginate.prev}
                        <a href="{link=novel.over.index page=$paginate.prev}"><span><</span></a>
                        {else}
                        <span class="disable"><</span>
                        {/if}
                        {loop=paginate.items}
                        <a href="{link=novel.over.index page=$loop.num}">
                            <span class="{$loop.status|default='','pt-pages-select'}">{$loop.num}</span>
                        </a>
                        {/loop}
                        {if $paginate.next}
                        <a href="{link=novel.over.index page=$paginate.next}"><span>></span></a>
                        {else}
                        <span class="disable">></span>
                        {/if}
                    </div>
                </div>
                {/if}
            </div>
        </div>
        <div class="fr w240">
            <!-- 周榜、月榜 -->
            <div class="pt-sexselect">
                {block method="rank.info" name=rankinfo key=weekvisit}
                <div class="pt-sexselect-title border-b"><span class="fl pt-sexselect-title-icon"></span>{$rankinfo.name}</div>
                <ul class="pt-sexselect-list">
                    {block method="novel.list" name=list order=$rankinfo.key num=20}
                    {section loop=$list item=$loop}
                    <li>
                        <span class="{=$i.index<3?'bg-red':'bg-ccc'} pt-sexselect-square">{=$i.index + 1}</span>
                        <a class="color5" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}">{$loop.novel.name}</a>
                        <a title="{$loop.author.name}" class="color3 fr" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a>
                    </li>
                    {/section}
                </ul>
            </div>
            <div class="pt-sexselect mt10">
                {block method="rank.info" name=rankinfo key=monthvisit}
                <div class="pt-sexselect-title border-b"><span class="fl pt-sexselect-title-icon"></span>{$rankinfo.name}</div>
                <ul class="pt-sexselect-list">
                    {block method="novel.list" name=list order=$rankinfo.key num=20}
                    {section loop=$list item=$loop}
                    <li>
                        <span class="{=$i.index<3?'bg-red':'bg-ccc'} pt-sexselect-square">{=$i.index + 1}</span>
                        <a class="color5" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}">{$loop.novel.name}</a>
                        <a title="{$loop.author.name}" class="color3 fr" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a>
                    </li>
                    {/section}
                </ul>
            </div>
            <!-- 新书推荐 -->
            <div class="fr pt-new-recomment">
                <div class="pt-new-recomment-title">新书推荐</div>
                <ul class="pt-new-recomment-list">
                    {block method="recommend" name=list recommendid=1 num=10}
                    {loop=$list}
                    <li>
                        <a title="{$loop.data.category.name}" class="color3" href="{link=novel.category.list categoryid=$loop.data.category.id key=$loop.data.category.key}">[{$loop.data.category.name}]</a>
                        <a href="{link=novel.novel.index novelid=$loop.data.novel.id pinyin=$loop.data.novel.pinyin}" class="color4 pt-text" title="{$loop.data.novel.name}">{$loop.data.novel.name}</a>
                    </li>
                    {/loop}
                </ul>
            </div>
        </div>
        <!-- 友情链接 -->
    </div>

    <!-- 底部版权-->
    {include file="/system/footer"}
</body>
</html>