<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>我的票夹 - 用户中心 - {$kx.config.sitename}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/style.css"/>
</head>
<body>
    <!-- 头部 -->
    {include file="/system/header"}
    <!-- 内容 -->
    <div class="pt-content">
        <!-- 面包屑 -->
        <div class="pt-crumb">
            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/images/crumb_icon.png" class="pt-crumb-icon">
            <span class="color5">
                <a href="{$kx.config.siteurl}">{$kx.config.sitename}</a> > <a href="{link=user.index.index}" class="color5">用户中心</a> > <a href="{link=user.vote.index}">我的推荐</a>
            </span>
        </div>
        <style>
            .pt-bar .pt-bar-item{
                float: left;
                width:131px;
                height:50px;
                line-height: 50px;
                text-align: center;
                background-color: #E5E5E5;
                border-top: 4px solid #E5E5E5;
                color: #929297;
            }
            .pt-bar .pt-bar-item.pt-active,
            .pt-bar .pt-bar-item:hover{
                background: #fff;
                border-top: 4px solid #f55;
                color: #323237;
            }
        </style>
        <!-- 一楼 -->
        <div class="pt-floor1">
            {include file="/system/userleft"}
            <div class="ml10 fl" style="width: 950px;">
                <ul class="pt-bar">
                    <a href="{link=user.assets.index}"><li class="pt-bar-item">资产概览</li></a>
                    <a href="{link=user.ticket.index}"><li class="pt-bar-item pt-active">我的票夹</li></a>
                    <a href="{link=user.pay.recharge}" class="bg-red color1 fr ptb5 plr20 mt10 mr10">
                        <img style="vertical-align: middle" src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/images/rmb.png" alt="充值">
                        <span>充值</span>
                    </a>
                </ul>
                <div class="clear"></div>
                <div class="bg-white plr20 ptb20">
                    <div class="size18 color32 bold">当前可用{$kx.config.user.ticket_caption}(张)</div>
                    <div class="color2 bold" style="font-size: 35px;">{$stat.surplus}</div>
                    <p>累计获得 {$stat.total} 张，共计投票 {$stat.used} 张，{$stat.expire} 张过期未使用。</p>
                </div>
                <div class="bg-white plr20 ptb20 mt20 pt-user-table" style="min-height: 415px;">
                    <h1 class="color32 size18 bold mb20">历史记录</h1>
                    {block method="pagination" name="paginate" page=$page limit=$pagesize count=$count maxpage=50 section=3}
                    {block method="user.ticketList" name=tickets userid=$userinfo.id page=$page}
                    <table>
                        <thead>
                        <tr>
                            <th>时间</th>
                            <th>数量</th>
                            <th>类别</th>
                            <th>备注</th>
                        </tr>
                        </thead>
                        <tbody>
                        {if empty($tickets)}
                        <tr>
                            <td colspan="4">您似乎来到了没有数据存在的荒原~~~</td>
                        </tr>
                        {else}
                        {section loop=$tickets item=$loop}
                        <tr>
                            <td>{$loop.create_time|date="Y-m-d"}</td>
                            <td><span class="bold" style="color: #{$loop.type|default="","F55","14B723"};">{$loop.type|default="","+","-"}{$loop.num}</span> 张</td>
                            <td>{$loop.type|default="未知","获得","投票"}</td>
                            <td>{=is_numeric($loop.ext)?$loop.ext.'消费返还':$loop.ext}</td>
                        </tr>
                        {/section}
                        {/if}
                        </tbody>
                    </table>
                    <!-- 分页 -->
                    {if !empty($tickets) && $paginate.total>1}
                    <div class="pt-pages">
                        <div class="pt30 color5">
                            {if $paginate.prev}
                            <a href="{link=user.vote.index page=$paginate.prev}"><span><</span></a>
                            {else}
                            <span class="disable"><</span>
                            {/if}
                            {loop=paginate.items}
                            <a href="{link=user.vote.index page=$loop.num}">
                                <span class="{$loop.status|default='','pt-pages-select'}">{$loop.num}</span>
                            </a>
                            {/loop}
                            {if $paginate.next}
                            <a href="{link=user.vote.index page=$paginate.next}"><span>></span></a>
                            {else}
                            <span class="disable">></span>
                            {/if}
                        </div>
                    </div>
                    {/if}
                </div>
            </div>
        </div>
    </div>

{include file="/system/footer"}
</body>
</html>