<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/css/global.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15 border-b">
    <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/return.png" class="pt-return" >
    <div class="size18 bold color37">新闻详情</div>
    <div>
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/ellipsis.png" class="mr5 pt-ellipsis">
    </div>
    <div class="pt5 pb5 pt-tip">
        <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
        <a href="{link=novel.search.index}" class="block color1 text-center pt-tip-item">搜索小说</a>
        <a href="{link=user.mark.index}" class="block color1 text-center pt-tip-item" rel="nofollow">我的书架</a>
        <a href="{link=user.index.index}" class="block color1 text-center pt-tip-item" rel="nofollow">个人中心</a>
    </div>
</div>
<!-- 内容 -->
<section class="relative color32 pt-read " style="padding-bottom: .2rem;padding-top:.1rem">
    <div class="size18 w100 text-center lh100  pb15">{$news.title}</div>
    <div class="size14 lh150 plr15 pt10 relative pt-read-cont">
        {$news.content}
    </div>
    <div class="size14 text-right plr15 mt10">{$news.user.name}</div>
    <div class="size14 text-right plr15 mt10">{$news.create_time|date="Y-m-d"}</div>
</section>
<!-- 底部版权 -->
{include file="/system/footer"}
<!-- 底部按钮 -->
{include file="/system/footerbutton"}
</body>
</html>