<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
	<title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
	<!-- 导航 -->
	<div class="flex-wrp flex-center bg-white w100 size14 pt-nav">
		<a href="{link=index.index}" class="color5 mr20 pt-select">精选</a>
		<a href="{link=novel.rank.index}" class="color5 mr20">排行</a>
		<a href="{link=novel.category.index}" class="color5 mr20">分类</a>
		<a href="{link=novel.over.index}" class="color5">完本</a>
	</div>

	<!-- 轮播 -->
	<div class="w100 pt-slider">
		<ul class="pt-slider-main">
            {block method="banner" name=list key='wap_index'}
            {loop=$list}
            <li class="pt-slider-panel">
                <a href="{$loop.url}" title="{$loop.intro}">
                    <img src="{$loop.img}" title="{$loop.intro}"  alt="{$loop.intro}" class="pt-slider-thumb">
                </a>
            </li>
            {/loop}
		</ul>
		<ul class="flex-wrp flex-center pt-slider-nav">
            {block method="banner" name=list key='wap_index'}
            {loop=$list}
            <li class="pt-slider-item"></li>
            {/loop}
	   </ul>
	</div>

	<!-- 搜索框 -->
	<div class="w100 bg-white pb10 plr15">
		<a href="{link=novel.search.index}" class="flex-wrp flex-center pt-search">
			<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/search.png" class="mr10 pt-search-icon" ><input type="text" class="color4" placeholder="请输入您要搜索的书名">
		</a>
	</div>

	<!-- 新书上架 -->
	<div class="w100 mb10 bg-white lh100 pt-new">
		<div class="size14 color7 bold pt-new-title">新书上架</div>
		<div class="w100 overflow-x">
			<div class="flex-wrp pt-new-cont">
                {block method="recommend" name=list recommendid=1 num=8}
                {loop=$list}
                <div class="size12 pt-new-item">
                    <a href="{link=novel.novel.index novelid=$loop.data.novel.id pinyin=$loop.data.novel.pinyin}"><img src="{$loop.data.novel.cover}" alt="{$loop.data.novel.name}"></a>
                    <div class="pt10 pb5"><a title="{$loop.data.novel.name}" href="{link=novel.novel.index novelid=$loop.data.novel.id pinyin=$loop.data.novel.pinyin}" class="compulsory-row-one color7">{$loop.data.novel.name}</a></div>
                    <div><a title="{$loop.data.author.name}" class="color4 compulsory-row-one" href="{link=author.space.index authorid=$loop.data.author.id pinyin=$loop.data.author.pinyin}">{$loop.data.author.name}</a></div>
                </div>
                {/loop}
			</div>
		</div>
	</div>

	<!-- 站长推荐 -->
	<div class="w100 bg-white lh100 pt-recomment">
		<div class="size14 color7 bold pt-recomment-title">站长推荐</div>
		<div class="pt-recomment-cont">
            {block method="recommend" name=list recommendid=2 num=3}
            {loop=$list}
			<div class="flex-wrp pt-recomment-item">
                <a href="{link=novel.novel.index novelid=$loop.data.novel.id pinyin=$loop.data.novel.pinyin}" class="mr15"><img src="{$loop.data.novel.cover}" alt="{$loop.data.novel.name}"></a>
				<div class="flex-item pt5" style="max-width: 2.65rem;">
					<div class="flex-wrp flex-between">
						<div class="size14 color7"><a title="{$loop.data.novel.name}" href="{link=novel.novel.index novelid=$loop.data.novel.id pinyin=$loop.data.novel.pinyin}" class="color7">{$loop.data.novel.name}</a></div>
						<div class="color2 size14">{$loop.data.data.mark} <span class="size12">人在追</span></div>
					</div>
					<div class="size12 compulsory-row mb10 mt10 lh130 color4">
                        {$loop.data.novel.intro|showIntroLine|truncate=50}
					</div>
					<div class="flex-wrp flex-between">
						<div class="size12 authorlabel"><a title="{$loop.data.author.name}" href="{link=author.space.index authorid=$loop.data.author.id pinyin=$loop.data.author.pinyin name=$loop.data.author.name}" class="color5">{$loop.data.author.name}</a></div>
						<div class="pt-recomment-label"><a title="{$loop.data.category.name}" href="{link=novel.category.list categoryid=$loop.data.category.id key=$loop.data.category.key}" class="color4">{$loop.data.category.name}</a></div>
					</div>
				</div>
			</div>
            {/loop}
		</div>
	</div>
    <!-- 专题 -->
    <div class="w100 mb10 bg-white lh100 pt-hotsort mt10">
        <div class="flex-wrp flex-between size14 color7 pt-hotsort-title" style="margin-bottom: .15rem;">
            <div class="bold">专题</div>
            <a href="{link=special.index}" class="size12 color4">更多 ></a>
        </div>
        {block method=special.list num=1 page=1 name=list}
        <a href="{link=special.detail specialid=$list[0]['id']}" title="{$list[0]['intro']}">
            <img src="{$list[0]['cover']}" alt="{$list[0]['intro']}" style="width: 345px;height: 135px; border-radius: 5pt;margin-left: 10px;">
        </a>
        <p style="margin:10px 10px 5px;font-size: 14px;">
            <span class="inline-block" style="width: 260px;">
                <span class="compulsory-row-one">{$list[0]['title']}</span>
            </span>
            <span class="fr">热度：{$list[0]['num_allvisit']}</span>
        </p>
    </div>
	<!-- 精品排行 -->
	<div class="w100 mb10 bg-white lh100 pt-hotsort mt10">
		<div class="flex-wrp flex-between size14 color7 pt-hotsort-title">
			<div class="bold">精品排行</div>
			<a href="{link=novel.rank.index}" class="size12 color4">更多 ></a>
		</div>
		<div class="flex-wrp pt-rank-list">
			<div class="border-r-red pt-rank-item pt-rank-select">点击榜</div>
			<div class="border-r-red pt-rank-item">推荐榜</div>
			<div class="pt-rank-item">收藏榜</div>
		</div>
		<div class="w100 overflow-x">
			<div class="flex-wrp pt-new-cont">
                {block method="novel.list" name=list order=weekvisit num=10}
                {loop}
				<div class="size12 pt-new-item">
                    <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" class="inline-block"><img src="{$loop.novel.cover}" alt="{$loop.novel.name}"></a>
                    <div class="w100 lh150 pt10 pb5 "><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color7 compulsory-row-one">{$loop.novel.name}</a></div>
                    <div class="w100 lh150 "><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color4 compulsory-row-one">{$loop.author.name}</a></div>
				</div>
                {/loop}
			</div>
            <div class="flex-wrp pt-new-cont none">
                {block method="novel.list" name=list order=vote num=10}
                {loop}
                <div class="size12 pt-new-item">
                    <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" class="inline-block"><img src="{$loop.novel.cover}" alt="{$loop.novel.name}"></a>
                    <div class="w100 lh150 pt10 pb5 "><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color7 compulsory-row-one">{$loop.novel.name}</a></div>
                    <div class="w100 lh150 "><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color4 compulsory-row-one">{$loop.author.name}</a></div>
                </div>
                {/loop}
            </div>
            <div class="flex-wrp pt-new-cont none">
                {block method="novel.list" name=list order=mark num=10}
                {loop}
                <div class="size12 pt-new-item">
                    <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" class="inline-block"><img src="{$loop.novel.cover}" alt="{$loop.novel.name}"></a>
                    <div class="w100 lh150 pt10 pb5 "><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color7 compulsory-row-one">{$loop.novel.name}</a></div>
                    <div class="w100 lh150 "><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color4 compulsory-row-one">{$loop.author.name}</a></div>
                </div>
                {/loop}
            </div>
		</div>
	</div>

	<!-- 最新更新 -->
	<div class="w100 bg-white lh100 pt-update">
		<div class="size14 bold color7 pt-update-title">最新更新</div>
		<div class="pt-update-cont">
            {block method="novel.list" name=list order=lastupdate num=5 cachetime=180}
            {loop}
            <div class="flex-wrp pt-update-item">
                <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" class="mr15"><img src="{$loop.novel.cover}" alt="{$loop.novel.name}"></a>
				<div class="flex-item" style="max-width: 2.65rem;">
					<div class="flex-wrp flex-between">
                        <div class="size14"><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}" class="color7">{$loop.novel.name}</a></div>
						<div class="color4 size12">{$loop.last.time|date="m-d H:i"}</div>
					</div>
					<div class="size12 compulsory-row-one mb5 mt5 lh120 ">
                        <a title="{$loop.last.name}" href="{link=novel.chapter.read novelid=$loop.novel.id pinyin=$loop.novel.pinyin chapterid=$loop.last.id}" class="color4">{$loop.last.name}</a>
					</div>
					<div class="flex-wrp flex-between">
                        <div class="size12 authorlabel"><a title="{$loop.author.name}" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}" class="color5">{$loop.author.name}</a></div>
                        <div class="pt-recomment-label"><a title="{$loop.category.name}" href="{link=novel.category.list categoryid=$loop.category.id key=$loop.category.key}" class="color4">{$loop.category.name}</a></div>
                    </div>
				</div>
			</div>
            {/loop}
        </div>
	</div>

	<!-- 底部版权 -->
    {include file="/system/footer"}
	<!-- 底部按钮 -->
	{include file="/system/footerbutton"}
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/index.js"></script>
</body>
</html>