<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>超级VIP - {$kx.config.sitename}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/css/global.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/js/flexible.min.js"></script>
</head>
<body>
<div class="w100">
    <div class="w100 bg-red flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/return-white2.png" class="pt-return">
        <div class="size18 color1">超级VIP</div>
        <div></div>
    </div>
    <div class="bg-red color1 pt10 pl20">
        <img src="{$userinfo.avatar}" alt="{=$userinfo.nickname?:$userinfo.name}" class="pt-avatar">
        <div class="inline-block pl10" style="position: absolute; margin-top: 7px;">
            {block method=user.isvip userid=$userinfo.id name=$isvip}
            {if $isvip}
            <h1 class="size16">尊敬的VIP会员您好</h1>
            <p class="size14">您的VIP于{$userinfo.vip_expire_time|date='Y-m-d'}日到期</p>
            {else}
            <h1 class="size16">尊敬的用户您好</h1>
            <p class="size14">您还未开通超级VIP</p>
            {/if}
        </div>
        <a class="fr mt15 mr10 color1" style="padding:0 10px;border: 2px solid #fff;border-radius: 20px;" href="{link=user.pay.vip}">{=$isvip?'续费VIP':'开通VIP'}</a>
    </div>
    <div class="bg-red bold pt20 mb10">
        <div class="pl10"></div>
        <div class="bg-white plr10 text-center ptb20" style="border-radius:20px 20px 0 0;">
            <div class="inline-block" style="border: 1px solid #e9e9e9;border-radius: 3px;padding: 10px;;">
                <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/vip_benefit_1.png" alt="折扣优惠" style="width: .3rem">
                <p class="color32">折扣优惠</p>
                <span class="size12">章节订阅更多折扣</span>
            </div>
            <div class="inline-block" style="border: 1px solid #e9e9e9;border-radius: 3px;padding: 10px;;">
                <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/vip_benefit_2.png" alt="首充大礼" style="width: .3rem">
                <p class="color32">首充大礼</p>
                <span class="size12">海量经验大放送</span>
            </div>
            <div class="inline-block" style="border: 1px solid #e9e9e9;border-radius: 3px;padding: 10px;;">
                <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/vip_benefit_3.png" alt="免费阅读" style="width: .3rem">
                <p class="color32">免费阅读</p>
                <span class="size12">海量书籍免费阅读</span>
            </div>
        </div>
    </div>

    <div class="bg-white mb10 pt-list pl10">
        <h1 class="color32 bold size16 pl10" style="border-left: 6px solid #f55;">VIP免费阅读</h1>
        {block method="novel.list" name=novellist userid=$userinfo.id num=10 type=2}
        {if empty($novellist)}
        <div class="flex-wrp pt-stick-item">
            您似乎来到了没有数据存在的荒原~~~
        </div>
        {else}
        <div class="free_for_vip size12">
            <div>
                <div class="color32">书籍名称</div>
                <div class="color32">作者</div>
                <div class="color32">分类</div>
                <div class="color32">字数</div>
            </div>
            {section loop=$novellist item=$loop}
            <div>
                <div><a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">《{$loop.novel.name}》</a></div>
                <div><a href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a></div>
                <div><a href="{link=novel.category.list categoryid=$loop.category.id key=$loop.category.key}">{$loop.category.name}</a></div>
                <div>{$loop.data.words}万</div>
            </div>
            {/section}
        </div>
        {/if}

    </div>
</div>

<!-- 底部版权 -->
{include file="/system/footer"}
</body>
</html>