<div class="pt-copyright">
    <div class="pt-copyright-line"></div>
    <div class="color2 aboutlink">
        {block method="page.list" name=list}
        {loop=$list}
        <a href="{link=page.detail pageid=$loop.id key=$loop.key}" title="{$loop.name}">{$loop.name}</a>
        {/loop}
    </div>
    <div class="color4 footer-info" style="margin-top:28px;">Copyright © 2009 - 2019 <a href="{$kx.config.siteurl}" target="_blank">{$kx.config.sitename}</a>. All Rights Reserved . 版权所有{$kx.config.sitename}</div>
    <div class="color4 footer-info">本站内容系{$kx.config.sitename}根据您的指令搜索各大小说站得到的链接列表，不代表{$kx.config.sitename}赞成被搜索网站的内容或立场</div>
    <div class="color4 footer-info">如果版权人认为在本站放置您的作品有损您的利益，请发邮件至“{if $kx.config.email}{$kx.config.email}{else}{$kx.config.qq}@qq.com{/if}”，本站确认后将会立即删除。</div>
    <div class="color4 footer-info">Power by <a href="http://www.ptcms.com" target="_blank">PT聚合小说搜索聚合程序 {$kx.PRO_VERSION} Build{$kx.PRO_TIME}</a>，模版设计：<a href="http://www.pakey.net" target="_blank">Pakey</a>，<a href="http://www.miitbeian.gov.cn/" target="_blank" rel="nofollow">{$kx.config.beian}</a></div>
    <div class="color4 footer-info">__RUNINFO__</div>
</div>
<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/jquery-3.3.1.js"></script>
<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/layer/layer.js"></script>
<div class="none">
    {$kx.config.tongji.pc}
    {if $kx.config.app.use_cdn}
    <script src="/api/stat/novel/info.js"></script>
    <script src="/api/stat/novel/read.js"></script>
    {/if}
</div>
