<div class="pt-list">
    <!-- 我的 -->
    <div class="fr pt-toplist">
        <div class="border-b size18 bold color8 pb10 pt-toplist-title">我的</div>
        <div class="pt-toplist-item">
            <a href="{link=user.index.index}"{if $userleftsign=='index'} class="color2"{/if}><span class="mr10">·</span>个人中心</a>
            <a href="{link=user.vip.index}"{if $userleftsign=='vip'} class="color2"{/if}><span class="mr10">·</span>超级会员</a>
            <a href="{link=user.assets.index}"{if in_array($userleftsign,['assets','ticket'])} class="color2"{/if}><span class="mr10">·</span>我的资产</a>
            <a href="{link=user.mark.index}"{if $userleftsign=='mark'} class="color2"{/if}><span class="mr10">·</span>我的书架</a>
            <a href="{link=user.history.index}"{if $userleftsign=='history'} class="color2"{/if}><span class="mr10">·</span>阅读历史</a>
            <a href="{link=user.booklist.index}"{if $userleftsign=='booklist'} class="color2"{/if}><span class="mr10">·</span>我的书单</a>
            <a href="{link=user.vote.index}"{if $userleftsign=='vote'} class="color2"{/if}><span class="mr10">·</span>我的推荐</a>
            <a href="{link=user.comment.publish}"{if $userleftsign=='comment'} class="color2"{/if}><span class="mr10">·</span>我的评论</a>
            <a href="{link=user.sign.index}"{if $userleftsign=='sign'} class="color2"{/if}><span class="mr10">·</span>我的签到</a>
            <a href="{link=user.star.index}"{if $userleftsign=='star'} class="color2"{/if}><span class="mr10">·</span>我的评分</a>
            <a href="{link=user.invite.index}"{if $userleftsign=='invite'} class="color2"{/if}><span class="mr10">·</span>我的邀请</a>
            <a href="{link=author.author.index}" target="_blank"><span class="mr10">·</span>原创专区</a>
        </div>
    </div>
    <!-- 设置 -->
    <div class="fr pt-toplist none">
        <div class="border-b bold size18 color8 pb10 pt-toplist-title">财务</div>
        <div class="pt-toplist-item">
            <a href="{link=user.charge.index}"{if $userleftsign=='charge'} class="color2"{/if}><span class="mr10">·</span>充值记录</a>
            <a href="{link=user.consume.index}"{if $userleftsign=='consume'} class="color2"{/if}><span class="mr10">·</span>消费记录</a>
            <a href="{link=user.reward.index}"{if $userleftsign=='reward'} class="color2"{/if}><span class="mr10">·</span>打赏记录</a>
            <a href="{link=user.distribution.index}"{if $userleftsign=='distribution'} class="color2"{/if}><span class="mr10">·</span>分销记录</a>
        </div>
    </div>
    <div class="fr pt-toplist">
        <div class="border-b bold size18 color8 pb10 pt-toplist-title">设置</div>
        <div class="pt-toplist-item">
            <a href="{link=user.info.index}"{if $userleftsign=='info'} class="color2"{/if}><span class="mr10">·</span>基础资料</a>
            <a href="{link=user.info.pwd}"{if $userleftsign=='pwd'} class="color2"{/if}><span class="mr10">·</span>修改密码</a>
            <a href="{link=user.info.bind}"{if $userleftsign=='bind'} class="color2"{/if}><span class="mr10">·</span>账号绑定</a>
            <a href="{link=user.auth.logout}"><span class="mr10">·</span>退出登录</a>
        </div>
    </div>
</div>
<style>
    .pt-rank:not(.pt-user){
        min-height: 630px;
    }
</style>