<?php defined('KX_ROOT') || exit('Permission denied');?><!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width,initial-scale=1.0" />
    <title><?php include \Kuxin\View::parseTpl($tkd['title']);?></title>
    <meta name="keywords" content="<?php include \Kuxin\View::parseTpl($tkd['keywords']);?>">
    <meta name="description" content="<?php include \Kuxin\View::parseTpl($tkd['description']);?>">
</head>
<body>
<script>
    setTimeout(function(){
        window.location.href='<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "mobileurl");?>'
    },0)
</script>
</body>
</html>
