<?php defined('KX_ROOT') || exit('Permission denied');?><!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title><?php include \Kuxin\View::parseTpl($tkd['title']);?></title>
    <meta name="keywords" content="<?php include \Kuxin\View::parseTpl($tkd['keywords']);?>">
    <meta name="description" content="<?php include \Kuxin\View::parseTpl($tkd['description']);?>">
    <link rel="stylesheet" href="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/css/global.css"/>
    <link rel="stylesheet" href="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/css/style.css"/>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url=<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "mobileurl");?><?php echo $_SERVER['REQUEST_URI'];?>">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "pcurl");?><?php echo $_SERVER['REQUEST_URI'];?>" />
</head>
<body>
<!-- 头部 -->
<div class="pt-top-nav">
    <ul class="content">
        <li class="fl">
            欢迎访问<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?>小说网
        </li>
        <li class="fr m">
            <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/images/shortcut_icon.png" class="pt-shortcut-icon">
            <span class="cursor color4 lh100" onclick="toDesktop('<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "siteurl");?>','<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?>')">桌面快捷</span>
        </li>
        <li class="fr mr20">
            <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/images/star_icon.png" class="pt-index-icon">
            <span class="cursor color4 lh100" onclick="addFavorite(document.title,window.location);">加入收藏</span>
        </li>
        <li class="fr mr20">
            <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/images/index_icon.png" class="pt-index-icon">
            <span class="cursor color4 lh100" onclick="setHome(this);">设为首页</span>
        </li>
    </ul>
</div>
<div class="w100 pt-head-bg">
    <div class="pt-head">
        <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/static/image/logo.png" class="pt-logo" title="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?>">
        <div class="pt-search-box">
            <form action="<?php echo \Kuxin\Helper\Url::build("novel.search.result",[],"");?>">
                <div class="pt-serachbg">
                    <input type="text" name="searchkey" placeholder="请输入您要搜索的书名" class="pt-serarch-input" value="<?php echo $_GET['searchkey'];?>">
                </div>
                <button type="submit" class="pt-search-btn">
                    <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/images/search.png" class="pt-search-icon">
                </button>
            </form>
        </div>
        <ul class="inline-block size14 color4 fr pt-head-list">
            <li>
                <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/images/person_icon.png" class="pt-person-icon">
                <?php if(($islogin)):?>
                <span class="color2 lh100">
                    <a href="<?php echo \Kuxin\Helper\Url::build("user.index.index",[],"");?>" class="color2"><?php echo $userinfo['nickname']?:$userinfo['name'];?></a>
                    <span>|</span>
                    <a href="<?php echo \Kuxin\Helper\Url::build("user.pay.recharge",[],"");?>" class="color2">充值</a>
                </span>
                <?php else:?>
                <span class="color2 lh100"><a title="登录" href="<?php echo \Kuxin\Helper\Url::build("user.auth.login",[],"");?>" class="color2">登录</a> | <a title="注册" href="<?php echo \Kuxin\Helper\Url::build("user.auth.register",[],"");?>" class="color2">注册</a></span>
                <?php endif;?>
            </li>
            <li>
                <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/images/book_icon.png" class="pt-book-icon">
                <a rel="nofollow" href="<?php echo \Kuxin\Helper\Url::build("user.mark.index",[],"");?>" class="color4 lh100">我的书架</a>
            </li>
            <li class="inline-block">
                <img src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/images/history_icon.png" class="pt-history-icon">
                <a rel="nofollow" href="<?php echo \Kuxin\Helper\Url::build("user.history.index",[],"");?>" class="color4 lh100">阅读历史</a>
            </li>
        </ul>
    </div>
</div>

<!-- 导航栏 -->
<div class="pt-navbg">
    <div class="pt-nav">
        <a title="首页" href="<?php echo \Kuxin\Helper\Url::build("index.index",[],"");?>"<?php if($pagesign=='index'):?> class="pt-active"<?php endif;?>>首页</a>
        <a title="排行" href="<?php echo \Kuxin\Helper\Url::build("novel.rank.index",[],"");?>"<?php if($pagesign=='rank'):?> class="pt-active"<?php endif;?>>排行</a>
        <a title="分类" href="<?php echo \Kuxin\Helper\Url::build("novel.category.index",[],"");?>"<?php if($pagesign=='category'):?> class="pt-active"<?php endif;?>>分类</a>
        <a title="完本" href="<?php echo \Kuxin\Helper\Url::build("novel.over.index",[],"");?>"<?php if($pagesign=='over'):?> class="pt-active"<?php endif;?>>完本</a>
        <a title="书单" href="<?php echo \Kuxin\Helper\Url::build("booklist.booklist.index",[],"");?>"<?php if($pagesign=='booklist'):?> class="pt-active"<?php endif;?>>书单</a>
        <a title="专题" href="<?php echo \Kuxin\Helper\Url::build("special.index",[],"");?>"<?php if($pagesign=='special'):?> class="pt-active"<?php endif;?>>专题</a>
        <a title="用户中心" href="<?php echo \Kuxin\Helper\Url::build("user.index.index",[],"");?>" class="fr<?php if($pagesign=='user'):?>  pt-active<?php endif;?>">用户中心</a>
        <a title="原创专区" href="<?php echo \Kuxin\Helper\Url::build("author.author.index",[],"");?>" class="fr" target="_blank">原创专区</a>
    </div>
</div>
<!-- 内容 -->
<div class="pt-content mt10">
    <!-- 一楼 -->
    <div class="pt-floor1 clearfix">
        <!-- 分类 -->
        <div class="fl pt-index-category mt10">
            <div class="pt-index-category-title">作品分类</div>
            <ul class="w100 pt-index-category-list">
                <?php $list=\Kuxin\Block::show('category.list', ['withall'=>0,'pid'=>1]);?>
                <?php if(is_array($list)): foreach($list as $key =>$loop):?>
                <li>
                    <a title="<?php echo $loop['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("novel.category.list",['categoryid'=>$loop['id'],'key'=>$loop['key']],"");?>">
                        <span class="color5 f_bold"><?php echo $loop['name'];?></span>
                        <span class="size12 color9"><?php echo $loop['num'];?></span>
                    </a>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
        <!-- 轮播 -->
        <div class="fl middle mt10">
            <div class="fl pt-slider">
                <ul class="pt-slider-main">
                    <?php $list=\Kuxin\Block::show('banner', ['key'=>'pc_index']);?>
                    <?php if(is_array($list)): foreach($list as $key =>$loop):?>
                    <li class="pt-slider-panel">
                        <a href="<?php echo $loop['url'];?>" title="<?php echo $loop['intro'];?>">
                            <img src="<?php echo $loop['img'];?>" title="<?php echo $loop['intro'];?>" class="pt-slider-thumb" alt="<?php echo $loop['intro'];?>">
                        </a>
                    </li>
                    <?php endforeach; endif;?>
                </ul>
                <ul class="pt-slider-nav">
                    <?php if(is_array($list)): foreach($list as $key =>$loop):?>
                    <li class="pt-slider-item"></li>
                    <?php endforeach; endif;?>
                </ul>
            </div>
            <div class="fl pt-news-list">
                <div class="title">新闻公告 <a href="<?php echo \Kuxin\Helper\Url::build("news.list",[],"");?>" class="fr size12 mr10 color9">更多 +</a></div>
                <ul class="list clearfix">
                    <?php $list=\Kuxin\Block::show('news.list', ['num'=>6]);?>
                    <?php if(is_array($list)): foreach($list as $key =>$loop):?>
                    <li>
                        <a title="<?php echo $loop['category']['name'];?>" href="#" target="_blank"> <span class="color3">[<?php echo $loop['category']['name'];?>]</span></a>
                        <a href="<?php echo \Kuxin\Helper\Url::build("news.detail",['newsid'=>$loop['id']],"");?>" title="<?php echo $loop['title'];?>" target="_blank"><span class="color4 pt-text"><?php echo $loop['title'];?></span></a>
                    </li>
                    <?php endforeach; endif;?>
                </ul>
            </div>
        </div>
        <!-- 新书推荐 -->
        <div class="fr pt-new-recomment mt10" style="height:370px">
            <div class="pt-new-recomment-title">新书推荐</div>
            <ul class="pt-new-recomment-list">
                <?php $list=\Kuxin\Block::show('recommend', ['recommendid'=>1,'num'=>10]);?>
                <?php if(is_array($list)): foreach($list as $key =>$loop):?>
                <li>
                    <a title="<?php echo $loop['data']['category']['name'];?>" class="color3 f_bold" href="<?php echo \Kuxin\Helper\Url::build("novel.category.list",['categoryid'=>$loop['data']['category']['id'],'key'=>$loop['data']['category']['key']],"");?>">[<?php echo $loop['data']['category']['name'];?>]</a>
                    <a href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['data']['novel']['id'],'pinyin'=>$loop['data']['novel']['pinyin']],"");?>" class="color4 pt-text" title="<?php echo $loop['data']['novel']['name'];?>"><?php echo $loop['data']['novel']['name'];?></a>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
    </div>
    <!-- 二楼 -->
    <div class="pt-floor2 mt20 clearfix">
        <!-- 站长推荐 -->
        <div class="pt-featured clearfix">
            <div class="pt-featured-title"><?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?>站长推荐</div>
            <ul class="pt-featured-list clearfix">
                <?php $list=\Kuxin\Block::show('recommend', ['recommendid'=>2,'num'=>6]);?>
                <?php if(is_array($list)): foreach($list as $key =>$loop):?>
                <li>
                    <a title="<?php echo $loop['data']['novel']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['data']['novel']['id'],'pinyin'=>$loop['data']['novel']['pinyin']],"");?>"><img src="<?php echo $loop['data']['novel']['cover'];?>" alt="<?php echo $loop['data']['novel']['name'];?>" title="<?php echo $loop['data']['novel']['name'];?>"></a>
                    <div class="pt-featured-list-cont">
                        <div><a href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['data']['novel']['id'],'pinyin'=>$loop['data']['novel']['pinyin']],"");?>" class="size16 color7 compulsory-row-one f_bold"><?php echo $loop['data']['novel']['name'];?></a></div>
                        <div class="size14 color8" style="margin-top:8px"> <strong>作者：</strong><a title="<?php echo $loop['data']['novel']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['data']['author']['id'],'pinyin'=>$loop['data']['author']['pinyin'],'name'=>$loop['data']['author']['name']],"");?>"><?php echo $loop['data']['author']['name'];?></a>
                        </div>
                        <div class="pt-featured-list-cont-intro compulsory-row-four size12 color9 mt10"><?php echo \Kuxin\Helper\Str::truncate(showIntroLine($loop['data']['novel']['intro']),50);?></div>
                        <div class="size12 color7"><a title="点击进入小说" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['data']['novel']['id'],'pinyin'=>$loop['data']['novel']['pinyin']],"");?>">前往阅读 >></a></div>
                    </div>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
        <!-- 点击榜 -->
        <div class="pt-sexselect ">
            <div class="size18 color4 w100  border-b" style="padding-bottom:8px;">
                <?php $rankinfo=\Kuxin\Block::show('rank.info', ['key'=>'weekvisit']);?>
                <span class="pt-sexselect-man pt-sexselect-active cursor"><?php echo $rankinfo['name'];?></span>
                <?php $rankinfo=\Kuxin\Block::show('rank.info', ['key'=>'monthvisit']);?>
                <span class="pt-sexselect-woman cursor"><?php echo $rankinfo['name'];?></span>
            </div>
            <ul class="pt-sexselect-list">
                <?php $list=\Kuxin\Block::show('novel.list', ['order'=>'weekvisit','num'=>12]);?>
                <?php if(is_array($list) && (array()!=$list)): $i=array(); $i['loop']=array_slice($list,0,null,true); $i['total']=count($list); $i['count']=count($i['loop']); $i['cols']=1; $i['add']=$i['count']%1?1-$i['count']%1:0; $i['order']=0; $i['row']=1;$i['col']=0;foreach(array_pad($i['loop'],$i['add'],array()) as $i['index']=>$i['list']): $loop=$i['list']; $i['order']++; $i['col']++; if($i['col']==1): $i['col']=0; $i['row']++; endif; $i['first']=$i['order']==1; $i['last']=$i['order']==$i['count']; $i['extra']=$i['order']>$i['count'];?>
                <li class="">
                    <span class="<?php echo $i['index']<3?'bg-red':'bg-ccc';?> pt-sexselect-square"><?php echo $i['index'] + 1;?></span>
                    <a class="color5  f_bold" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin']],"");?>" title="<?php echo $loop['novel']['name'];?>"><?php echo $loop['novel']['name'];?></a>
                    <a title="<?php echo $loop['author']['name'];?>" class="color9 fr " href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['author']['id'],'pinyin'=>$loop['author']['pinyin'],'name'=>$loop['author']['name']],"");?>"><?php echo $loop['author']['name'];?></a>
                </li>
                <?php endforeach; endif;?>
            </ul>
            <ul class="pt-sexselect-list none">
                <?php $list=\Kuxin\Block::show('novel.list', ['order'=>'monthvisit','num'=>12]);?>
                <?php if(is_array($list) && (array()!=$list)): $i=array(); $i['loop']=array_slice($list,0,null,true); $i['total']=count($list); $i['count']=count($i['loop']); $i['cols']=1; $i['add']=$i['count']%1?1-$i['count']%1:0; $i['order']=0; $i['row']=1;$i['col']=0;foreach(array_pad($i['loop'],$i['add'],array()) as $i['index']=>$i['list']): $loop=$i['list']; $i['order']++; $i['col']++; if($i['col']==1): $i['col']=0; $i['row']++; endif; $i['first']=$i['order']==1; $i['last']=$i['order']==$i['count']; $i['extra']=$i['order']>$i['count'];?>
                <li>
                    <span class="<?php echo $i['index']<3?'bg-red':'bg-ccc';?> pt-sexselect-square"><?php echo $i['index'] + 1;?></span>
                    <a class="color5  f_bold" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin']],"");?>" title="<?php echo $loop['novel']['name'];?>"><?php echo $loop['novel']['name'];?></a>
                    <a title="<?php echo $loop['author']['name'];?>" class="color9 fr " href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['author']['id'],'pinyin'=>$loop['author']['pinyin'],'name'=>$loop['author']['name']],"");?>"><?php echo $loop['author']['name'];?></a>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
    </div>
    <!-- 三楼 -->
    <div class="pt-floor3 clearfix">
        <!-- 分类 -->
        <div class="pt-sort mt10">
            <?php $list=\Kuxin\Block::show('category.list', ['withall'=>0,'pid'=>1,'num'=>9]);?>
            <?php if(is_array($list)): foreach($list as $key =>$loop):?>
            <div class="pt-sort-cont clearfix" style="width: 290px;min-height: 281px;">
                <div class="pt-sort-cont-title">
                    <span class="fl pt-sort-cont-title-icon"></span>
                    <a title="<?php echo $loop['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("novel.category.list",['categoryid'=>$loop['id'],'key'=>$loop['key']],"");?>" class="size18 color3 f_bold"><?php echo $loop['name'];?></a>
                </div>
                <?php $novellist=\Kuxin\Block::show('novel.list', ['num'=>5,'category'=>$loop['id']]);?>
                <?php if(is_array($novellist) && (array()!=$novellist)): $i=array(); $i['loop']=array_slice($novellist,0,null,true); $i['total']=count($novellist); $i['count']=count($i['loop']); $i['cols']=1; $i['add']=$i['count']%1?1-$i['count']%1:0; $i['order']=0; $i['row']=1;$i['col']=0;foreach(array_pad($i['loop'],$i['add'],array()) as $i['index']=>$i['list']): $nlist=$i['list']; $i['order']++; $i['col']++; if($i['col']==1): $i['col']=0; $i['row']++; endif; $i['first']=$i['order']==1; $i['last']=$i['order']==$i['count']; $i['extra']=$i['order']>$i['count'];?>
                <?php if($i['first']):?>
                <div class="pt-sort-top">
                    <a href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$nlist['novel']['id'],'pinyin'=>$nlist['novel']['pinyin']],"");?>" title="<?php echo $nlist['novel']['name'];?>"><img src="<?php echo $nlist['novel']['cover'];?>" alt="<?php echo $loop['data']['novel']['name'];?>"></a>
                    <div class="pt-sort-top-r">
                        <div class="size16 color7">
                            <a href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$nlist['novel']['id'],'pinyin'=>$nlist['novel']['pinyin']],"");?>" title="<?php echo $nlist['novel']['name'];?>" class="size16 color7 fl compulsory-row-one"><?php echo $nlist['novel']['name'];?></a>
                        </div>
                        <div class="compulsory-row-three size12 color4 pt-sort-r-intro"><?php echo \Kuxin\Helper\Str::truncate(showIntroLine($nlist['novel']['intro']),"50");?></div>

                        <div class="size14 color4">
                            <a title="<?php echo $nlist['author']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$nlist['author']['id'],'pinyin'=>$nlist['author']['pinyin'],'name'=>$nlist['author']['name']],"");?>" class="size14 color4 "><?php echo $nlist['author']['name'];?></a>著
                        </div>
                    </div>
                </div>
                <?php else:?>
                <!-- 分类列表 -->
                <div class="pt-sort-list clearfix">
                    <a style="width:200px;" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$nlist['novel']['id'],'pinyin'=>$nlist['novel']['pinyin']],"");?>" title="<?php echo $nlist['novel']['name'];?>" class="inline-block  fl compulsory-row-one color5"><?php echo $nlist['novel']['name'];?></a>
                    <a style="width:80px;" title="<?php echo $nlist['author']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$nlist['author']['id'],'pinyin'=>$nlist['author']['pinyin'],'name'=>$nlist['author']['name']],"");?>" class="inline-block compulsory-row-one fr color4"><?php echo $nlist['author']['name'];?></a>
                </div>
                <?php endif;?>
                <?php endforeach; endif;?>
            </div>
            <?php endforeach; endif;?>
        </div>
        <!-- 推荐榜 -->
        <div class="pt-sexselect mt10">
            <?php $rankinfo=\Kuxin\Block::show('rank.info', ['key'=>'vote']);?>
            <div class="pt-sexselect-title border-b"><span class="fl pt-sexselect-title-icon"></span><?php echo $rankinfo['name'];?></div>
            <ul class="pt-sexselect-list">
                <?php $list=\Kuxin\Block::show('novel.list', ['order'=>$rankinfo['key'],'num'=>15]);?>
                <?php if(is_array($list) && (array()!=$list)): $i=array(); $i['loop']=array_slice($list,0,null,true); $i['total']=count($list); $i['count']=count($i['loop']); $i['cols']=1; $i['add']=$i['count']%1?1-$i['count']%1:0; $i['order']=0; $i['row']=1;$i['col']=0;foreach(array_pad($i['loop'],$i['add'],array()) as $i['index']=>$i['list']): $loop=$i['list']; $i['order']++; $i['col']++; if($i['col']==1): $i['col']=0; $i['row']++; endif; $i['first']=$i['order']==1; $i['last']=$i['order']==$i['count']; $i['extra']=$i['order']>$i['count'];?>
                <li class="">
                    <span class="<?php echo $i['index']<3?'bg-red':'bg-ccc';?> pt-sexselect-square"><?php echo $i['index'] + 1;?></span>
                    <a class="color5 f_bold" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin']],"");?>" title="<?php echo $loop['novel']['name'];?>"><?php echo $loop['novel']['name'];?></a>
                    <a title="<?php echo $loop['author']['name'];?>" class="color9 fr" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['author']['id'],'pinyin'=>$loop['author']['pinyin'],'name'=>$loop['author']['name']],"");?>"><?php echo $loop['author']['name'];?></a>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
        <!-- 收藏榜 -->
        <div class="pt-sexselect mt20">
            <?php $rankinfo=\Kuxin\Block::show('rank.info', ['key'=>'mark']);?>
            <div class="pt-sexselect-title border-b"><span class="fl pt-sexselect-title-icon"></span><?php echo $rankinfo['name'];?></div>
            <ul class="pt-sexselect-list">
                <?php $list=\Kuxin\Block::show('novel.list', ['order'=>$rankinfo['key'],'num'=>10]);?>
                <?php if(is_array($list) && (array()!=$list)): $i=array(); $i['loop']=array_slice($list,0,null,true); $i['total']=count($list); $i['count']=count($i['loop']); $i['cols']=1; $i['add']=$i['count']%1?1-$i['count']%1:0; $i['order']=0; $i['row']=1;$i['col']=0;foreach(array_pad($i['loop'],$i['add'],array()) as $i['index']=>$i['list']): $loop=$i['list']; $i['order']++; $i['col']++; if($i['col']==1): $i['col']=0; $i['row']++; endif; $i['first']=$i['order']==1; $i['last']=$i['order']==$i['count']; $i['extra']=$i['order']>$i['count'];?>
                <li class="">
                    <span class="<?php echo $i['index']<3?'bg-red':'bg-ccc';?> pt-sexselect-square"><?php echo $i['index'] + 1;?></span>
                    <a class="color5 f_bold" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin']],"");?>" title="<?php echo $loop['novel']['name'];?>"><?php echo $loop['novel']['name'];?></a>
                    <a title="<?php echo $loop['author']['name'];?>" class="color9 fr" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['author']['id'],'pinyin'=>$loop['author']['pinyin'],'name'=>$loop['author']['name']],"");?>"><?php echo $loop['author']['name'];?></a>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
    </div>
    <!-- 四楼楼 -->
    <div class="pt-floor4 clearfix">
        <!-- 章节更新 -->
        <div class="pt-update">
            <div class="pt-update-title"><?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?>最新更新</div>
            <ul class="pt-update-list">
                <?php $list=\Kuxin\Block::show('novel.list', ['order'=>'lastupdate','num'=>25,'cachetime'=>180]);?>
                <?php if(is_array($list)): foreach($list as $key =>$loop):?>
                <li class="clear <?php if($key%2):?>bg-f9<?php endif;?>">
                    <a title="<?php echo $loop['category']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("novel.category.list",['categoryid'=>$loop['category']['id'],'key'=>$loop['category']['key']],"");?>" class="category"> [<?php echo $loop['category']['name'];?>] </a>
                    <a title="<?php echo $loop['novel']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin']],"");?>" class="novelname size16 "><?php echo $loop['novel']['name'];?></a>
                    <a title="<?php echo $loop['last']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("novel.chapter.read",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin'],'chapterid'=>$loop['last']['id']],"");?>" class="chaptername"><?php echo $loop['last']['name'];?></a>
                    <a title="<?php echo $loop['author']['name'];?>" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['author']['id'],'pinyin'=>$loop['author']['pinyin'],'name'=>$loop['author']['name']],"");?>" class="color7 author"><?php echo $loop['author']['name'];?></a>
                    <span class="time"><?php echo \Kuxin\View::date($loop['last']['time'],"m-d H:i");?></span>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
        <!-- 新书榜 -->
        <div class="pt-sexselect mt10">
            <?php $rankinfo=\Kuxin\Block::show('rank.info', ['key'=>'postdate']);?>
            <div class="pt-sexselect-title border-b"><span class="fl pt-sexselect-title-icon"></span><?php echo $rankinfo['name'];?></div>
            <ul class="pt-sexselect-list">
                <?php $list=\Kuxin\Block::show('novel.list', ['order'=>$rankinfo['key'],'num'=>15]);?>
                <?php if(is_array($list) && (array()!=$list)): $i=array(); $i['loop']=array_slice($list,0,null,true); $i['total']=count($list); $i['count']=count($i['loop']); $i['cols']=1; $i['add']=$i['count']%1?1-$i['count']%1:0; $i['order']=0; $i['row']=1;$i['col']=0;foreach(array_pad($i['loop'],$i['add'],array()) as $i['index']=>$i['list']): $loop=$i['list']; $i['order']++; $i['col']++; if($i['col']==1): $i['col']=0; $i['row']++; endif; $i['first']=$i['order']==1; $i['last']=$i['order']==$i['count']; $i['extra']=$i['order']>$i['count'];?>
                <li class="">
                    <span class="<?php echo $i['index']<3?'bg-red':'bg-ccc';?> pt-sexselect-square "><?php echo $i['index'] + 1;?></span>
                    <a class="color5 f_bold" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin']],"");?>" title="<?php echo $loop['novel']['name'];?>"><?php echo $loop['novel']['name'];?></a>
                    <a title="<?php echo $loop['author']['name'];?>" class="color9 fr" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['author']['id'],'pinyin'=>$loop['author']['pinyin'],'name'=>$loop['author']['name']],"");?>"><?php echo $loop['author']['name'];?></a>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
        <!-- 下载榜 -->
        <div class="pt-sexselect mt10">
            <?php $rankinfo=\Kuxin\Block::show('rank.info', ['key'=>'down']);?>
            <div class="pt-sexselect-title border-b"><span class="fl pt-sexselect-title-icon"></span><?php echo $rankinfo['name'];?></div>
            <ul class="pt-sexselect-list">
                <?php $list=\Kuxin\Block::show('novel.list', ['order'=>$rankinfo['key'],'num'=>15]);?>
                <?php if(is_array($list) && (array()!=$list)): $i=array(); $i['loop']=array_slice($list,0,null,true); $i['total']=count($list); $i['count']=count($i['loop']); $i['cols']=1; $i['add']=$i['count']%1?1-$i['count']%1:0; $i['order']=0; $i['row']=1;$i['col']=0;foreach(array_pad($i['loop'],$i['add'],array()) as $i['index']=>$i['list']): $loop=$i['list']; $i['order']++; $i['col']++; if($i['col']==1): $i['col']=0; $i['row']++; endif; $i['first']=$i['order']==1; $i['last']=$i['order']==$i['count']; $i['extra']=$i['order']>$i['count'];?>
                <li class="">
                    <span class="<?php echo $i['index']<3?'bg-red':'bg-ccc';?> pt-sexselect-square"><?php echo $i['index'] + 1;?></span>
                    <a class="color5 f_bold" href="<?php echo \Kuxin\Helper\Url::build("novel.novel.index",['novelid'=>$loop['novel']['id'],'pinyin'=>$loop['novel']['pinyin']],"");?>" title="<?php echo $loop['novel']['name'];?>"><?php echo $loop['novel']['name'];?></a>
                    <a title="<?php echo $loop['author']['name'];?>" class="color9 fr" href="<?php echo \Kuxin\Helper\Url::build("author.space.index",['authorid'=>$loop['author']['id'],'pinyin'=>$loop['author']['pinyin'],'name'=>$loop['author']['name']],"");?>"><?php echo $loop['author']['name'];?></a>
                </li>
                <?php endforeach; endif;?>
            </ul>
        </div>
    </div>
    <!-- 友情链接 -->
    <div class="pt-blogroll">
        <div class="pt-blogroll-title">
            <span>友情链接</span>
        </div>
        <div class="pt-blogroll-list">
            <?php $list=\Kuxin\Block::show('friendlink.list', []);?>
            <?php if(is_array($list)): foreach($list as $key =>$loop):?>
            <a href="<?php echo $loop['url'];?>" target="_blank" class="color4" <?php if(!empty($loop['color'])):?> style="color: <?php echo $loop['color'];?>;" <?php endif;?> title="<?php echo $loop['name'];?><?php echo $loop['intro'];?>">
            <?php echo \Kuxin\View::default($loop['is_bold'],'','<strong>');?><?php echo $loop['name'];?><?php echo \Kuxin\View::default($loop['is_bold'],'','</strong>');?>
            </a>
            <?php endforeach; endif;?>
        </div>
    </div>
</div>
<!-- 底部版权-->
<div class="pt-copyright">
    <div class="pt-copyright-line"></div>
    <div class="color2 aboutlink">
        <?php $list=\Kuxin\Block::show('page.list', []);?>
        <?php if(is_array($list)): foreach($list as $key =>$loop):?>
        <a href="<?php echo \Kuxin\Helper\Url::build("page.detail",['pageid'=>$loop['id'],'key'=>$loop['key']],"");?>" title="<?php echo $loop['name'];?>"><?php echo $loop['name'];?></a>
        <?php endforeach; endif;?>
    </div>
    <div class="color4 footer-info" style="margin-top:28px;">Copyright © 2009 - 2019 <a href="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "siteurl");?>" target="_blank"><?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?></a>. All Rights Reserved . 版权所有<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?></div>
    <div class="color4 footer-info">本站内容系<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?>根据您的指令搜索各大小说站得到的链接列表，不代表<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "sitename");?>赞成被搜索网站的内容或立场</div>
    <div class="color4 footer-info">如果版权人认为在本站放置您的作品有损您的利益，请发邮件至“<?php if(\Kuxin\Helper\Arr::getValue($_kxcms_config, "email")):?><?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "email");?><?php else:?><?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "qq");?>@qq.com<?php endif;?>”，本站确认后将会立即删除。</div>
    <div class="color4 footer-info">Power by <a href="http://www.ptcms.com" target="_blank">PT聚合小说搜索聚合程序 <?php echo PRO_VERSION;?> Build<?php echo PRO_TIME;?></a>，模版设计：<a href="http://www.pakey.net" target="_blank">Pakey</a>，<a href="http://www.miitbeian.gov.cn/" target="_blank" rel="nofollow"><?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "beian");?></a></div>
    <div class="color4 footer-info"><?php echo \Kuxin\Response::runinfo();?></div>
</div>
<script src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/js/jquery-3.3.1.js"></script>
<script src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/js/layer/layer.js"></script>
<div class="none">
    <?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "tongji.pc");?>
    <?php if(\Kuxin\Helper\Arr::getValue($_kxcms_config, "app.use_cdn")):?>
    <script src="/api/stat/novel/info.js"></script>
    <script src="/api/stat/novel/read.js"></script>
    <?php endif;?>
</div>

<!-- js-->
<script src="<?php echo \Kuxin\Helper\Arr::getValue($_kxcms_config, "resurl");?>/template/kxwebno1/js/index.js"></script>
</body>
</html>