<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
    <style>

    </style>
</head>
<body>
	<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
		<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return" onclick="window.history.back();">
		<div class="size18 bold color37">书单详情</div>
        <div>
            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/ellipsis.png" class="mr5 pt-ellipsis">
        </div>
        <div class="pt5 pb5 pt-tip">
            <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
            <a href="{link=user.booklist.detail}" class="block color1 text-center pt-tip-item">创建书单</a>
            <a href="{link=user.booklist.index}" class="block color1 text-center pt-tip-item">我的书单</a>
        </div>
	</div>
    <div>
        <div class="plr15 bg-white pb30">
            <h3 class="color37">{$booklist.title} </h3>
            <span class="color62 size14">作者：{=$booklist.user.nickname?:$booklist.user.name} <span class="fr color92">{$booklist.create_time|date='Y-m-d H:i'}</span></span>
            <div style="max-height: 72px;overflow: hidden;position:relative" class="tags color62 size14">
                标签：
                {loop=$booklist.tags}
                <a title="{$loop.name}" href="{link=index tagid=$loop.id}" class="mt10 color2 plr5">{$loop.name}</a>
                {/loop}
            </div>
            <div class="compulsory-row-three pt-bookdetail-intro size14 pt10">
               <span class="color62">书单简介：</span>{$booklist.intro|showIntroLine}
            </div>
            <div class="stat size12 pt10">
                书籍 <span class="color2">{$booklist.num_novel}</span><span class="color3 plr5">/</span>
                浏览 <span class="color2">{$booklist.num_allvisit}</span><span class="color3 plr5">/</span>
                收藏 <span class="color2">{$booklist.num_mark}</span>
            </div>
        </div>
        <style>
            .pt-booklist-novels li{
                background-color: #fff;
            }
            .pt-booklist-novels li:first-child{
                border-top: 1px solid #eee;
            }
            .pt-booklist-novels li:last-child{
                margin-bottom: 50px;
            }
            .pt-booklist-novels li .pt-novel-cover{
                width: 110px;
                height: 150px;
            }
            .pt-novel-comment{
                height:63px;
                border:1px solid #E9E9E9;
            }
        </style>
        <ul class="pt-booklist-novels">
            {loop=$booklist.novels}
            <li class="pt-novels plr15 pb15">
                <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
                    <div class="flex-wrp pt-popular-item">
                        <img src="{$loop.novel.cover}" class="mr15" alt="{$loop.novel.name}">
                        <div class="flex-item pt5">
                            <div class="flex-wrp flex-between">
                                <div class="size14">
                                    <span class="color7">{$loop.novel.name}</span>
                                </div>
                            </div>
                            <div class="size12 pt5">
                                <span class="mr30">{$loop.author.name}</span>  {$loop.category.name} | <span class="color2">{$loop.data.allvisit}</span> 人在读
                            </div>
                            <div class="size12 pt10">
                                <span class="color32 size14">推荐指数:</span>
                                <span class="pt-photo">
                                    <span title="不知所云">
                                        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/star{=$loop.star>=1?'1':''}.png" class="{=$loop.star>=1?'':'no'}high">
                                    </span>
                                    <span title="随便看看">
                                        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/star{=$loop.star>=2?'1':''}.png" class="{=$loop.star>=2?'':'no'}high">
                                    </span>
                                    <span title="值得一读">
                                        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/star{=$loop.star>=3?'1':''}.png" class="{=$loop.star>=3?'':'no'}high">
                                    </span>
                                    <span title="不容错过">
                                        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/star{=$loop.star>=4?'1':''}.png" class="{=$loop.star>=4?'':'no'}high">
                                    </span>
                                    <span title="经典必读">
                                        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/star{=$loop.star>=5?'1':''}.png" class="{=$loop.star>=5?'':'no'}high">
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="pt-novel-comment compulsory-row plr10 ptb10 size14">
                        {$loop.comment|showIntroLine}
                    </div>
                </a>
            </li>
            {/loop}
        </ul>
    </div>
    <style>
        .pt-tabbar .pt-tabbar-item{
            padding:10px 0 10px 20px;
            background-size: 16px 16px !important;
            background-position: 0 50% !important;
        }
        .pt-tabbar .pt-tabbar-vote{
            background: url("{$kx.config.pcurl}/template/kxmobileno1/images/praise2.png") no-repeat;
        }
        .pt-tabbar .pt-tabbar-mark{
            background: url("{$kx.config.pcurl}/template/kxmobileno1/images/mark2.png") no-repeat;
        }
        .pt-tabbar .pt-tabbar-comment{
            background: url("{$kx.config.pcurl}/template/kxmobileno1/images/comment2.png") no-repeat;
        }
    </style>
    <div class="w100 flex-wrp flex-between size14 color4 flex-align-center pt-tabbar">
        {block method=user.isvote type='booklist' booklistid=$booklist.id name=$isvote userid=$userinfo.id}
        {if $isvote}
        <a class="pt-tabbar-item pt-tabbar-vote" href="{link=user.vote.del type='booklist' booklistid=$booklist.id}">
            <div class="lh100">取消推荐({$booklist.num_vote})</div>
        </a>
        {else}
        <a class="pt-tabbar-item pt-tabbar-vote" href="{link=user.vote.add type='booklist' booklistid=$booklist.id}">
           <div class="lh100">推荐({$booklist.num_vote})</div>
        </a>
        {/if}
        {block method=mark.check type='booklist' booklistid=$booklist.id name=$ismark userid=$userinfo.id}
        {if $ismark}
        <a class="pt-tabbar-item pt-tabbar-mark" href="{link=user.mark.del type='booklist' booklistid=$booklist.id}">
            <div class="lh100">取消收藏({$booklist.num_mark})</div>
        </a>
        {else}
        <a class="pt-tabbar-item pt-tabbar-mark" href="{link=user.mark.add type='booklist' booklistid=$booklist.id}">
            <div class="lh100">收藏({$booklist.num_mark})</div>
        </a>
        {/if}
        <a class="pt-tabbar-item pt-tabbar-comment" href="{link=booklist.comment.list booklistid=$booklist.id}">
            <div class="lh100">留言({$booklist.num_comment})</div>
        </a>
    </div>
</body>
{if $kx.config.app.use_cdn}
<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/api/stat/booklist/info.js"></script>
{/if}
</html>