<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
	<!-- 推荐榜 -->
	<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
		<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return" onclick="window.history.back();">
		<div class="size18 bold color37">{$category.name}</div>
        <div>
            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/ellipsis.png" class="mr5 pt-ellipsis">
        </div>
        <div class="pt5 pb5 pt-tip">
            <a href="{link=novel.category.index}" class="block color1 text-center pt-tip-item" title="{$novel.name}">返回分类</a>
            <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
            <a href="{link=novel.search.index}" class="block color1 text-center pt-tip-item">搜索小说</a>
            <a href="{link=user.mark.index}" class="block color1 text-center pt-tip-item" rel="nofollow">我的书架</a>
            <a href="{link=user.index.index}" class="block color1 text-center pt-tip-item" rel="nofollow">个人中心</a>
        </div>
	</div>
    <div class="pt-popular-cont mt10">
        {block method="pagination" name="paginate" page=$page limit=$pagesize count=$category.num maxpage=50 section=3}
        {block method="novel.list" name=list category=$category.id order=weekvisit num=$paginate.limit page=$paginate.current}
        {section loop=$list item=$loop}
        <div class="flex-wrp pt-popular-item">
            <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
                <img src="{$loop.novel.cover}" class="mr15" alt="{$loop.novel.name}">
            </a>
            <div class="flex-item pt5" style="max-width: 2.65rem;">
                <div class="flex-wrp flex-between">
                    <div class="size14 ">
                        <a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color7">{$loop.novel.name}</a>
                    </div>
                    <div class="color2 size14">{$loop.data.mark} <span class="size12">人在追</span></div>
                </div>
                <div class="size12 compulsory-row mb10 mt10 lh130 color4">
                    {$loop.novel.intro|showIntroLine}
                </div>
                <div class="flex-wrp flex-between">
                    <div class="size12">
                        <a title="{$loop.author.name}" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}" class="color5">{$loop.author.name}</a>
                    </div>
                    <div class="pt-popular-label">
                        <a title="{$loop.category.name}" href="{link=novel.category.list id=$loop.category.id key=$loop.category.key}" class="color4">{$loop.category.name}</a>
                    </div>
                </div>
            </div>
        </div>
        {/section}
    </div>
    {if $paginate.total > 1}
    <div class="flex-wrp flex-between bg-white ptb15 plr15 mt10">
        {if $paginate.first != $paginate.current}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.category.list categoryid=$category.id key=$category.key page=$paginate.first}">
                <span class="size14 color2">首页</span>
            </a>
        </div>
        {/if}
        {if $paginate.prev}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.category.list categoryid=$category.id key=$category.key page=$paginate.prev}">
                <span class="size14 color2">上一页</span>
            </a>
        </div>
        {/if}
        {if $paginate.next}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.category.list categoryid=$category.id key=$category.key page=$paginate.next}">
                <span class="size14 color2">下一页</span>
            </a>
        </div>
        {/if}
        {if $paginate.last != $paginate.current}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.category.list categoryid=$category.id key=$category.key page=$paginate.last}">
                <span class="size14 color2">尾页</span>
            </a>
        </div>
        {/if}
    </div>
    {/if}

    <!-- 底部版权 -->
    {include file="/system/footer"}
</body>
</html>