<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body> 
	<!-- 导航 -->
    <div class="flex-wrp flex-center bg-white w100 size14 pt-nav">
        <a href="{link=index.index}" class="color5 mr20">精选</a>
        <a href="{link=novel.rank.index}" class="color5 mr20">排行</a>
        <a href="{link=novel.category.index}" class="color5 mr20 pt-select">分类</a>
        <a href="{link=novel.over.index}" class="color5">完本</a>
    </div>
	
	<!-- 分类 -->
	<div class="mb70">
        {block method="category.list" name=categoryList pid=1 withall=0}
        {loop=categoryList}
		<div class="mt10 bg-white plr15">
			<div class="w100 pb10 pt10 lh100 border-b flex-wrp flex-between">
				<div class="pl10 border-l-red">
					<a title="{$loop.name}" class="size16 color7 mr10" href="{link=novel.category.list categoryid=$loop.id key=$loop.key}">{$loop.name}</a>
					<span class="size12 color4">共{$loop.num}本</span>
				</div>
				<a class="size12 color4 pt-youjiantou" href="{link=novel.category.list categoryid=$loop.id key=$loop.key}" title="{$loop.name}">></a>
			</div>
            <div class="w100 overflow-x mt10 mb10">
                <div class="flex-wrp pt-new-cont">
                    {block method="novel.list" name=list order=weekvisit num=10 category=$loop.id}
                    {section loop=$list item=$novellist}
                    <div class="size12 pt-new-item">
                        <a href="{link=novel.novel.index novelid=$novellist.novel.id pinyin=$novellist.novel.pinyin}" title="{$novellist.novel.name}" class="inline-block"><img src="{$novellist.novel.cover}"></a>
                        <div class="w100 lh150 pt10 pb5 "><a title="{$novellist.novel.name}" href="{link=novel.novel.index novelid=$novellist.novel.id pinyin=$novellist.novel.pinyin}" class="color7 compulsory-row-one">{$novellist.novel.name}</a></div>
                        <div class="w100 lh150 "><a title="{$novellist.author.name}" href="{link=novel.novel.index novelid=$novellist.novel.id pinyin=$novellist.novel.pinyin}" class="color4 compulsory-row-one">{$novellist.author.name}</a></div>
                    </div>
                    {/section}
                </div>
            </div>
		</div>
        {/loop}
	</div>

    <!-- 底部版权 -->
    {include file="/system/footer"}
    <!-- 底部按钮 -->
    {include file="/system/footerbutton"}
	<!-- js -->
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/jquery-3.3.1.js"></script>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/index.js"></script>
</body>
</html>