<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
	<!-- 导航 -->
    <div class="flex-wrp flex-center bg-white w100 size14 pt-nav">
        <a href="{link=index.index}" class="color5 mr20">精选</a>
        <a href="{link=novel.rank.index}" class="color5 mr20">排行</a>
        <a href="{link=novel.category.index}" class="color5 mr20">分类</a>
        <a href="{link=novel.over.index}" class="color5 pt-select">完本</a>
    </div>


	<!-- 热门完本 -->
    <div style="margin-bottom: 0.56rem;">
        <div class="w100 bg-white lh100 pt-finish mt10">
            <div class="pt-finish-cont">
                {block method="pagination" name="paginate" page=$page limit=$pagesize count=$count maxpage=50 section=3}
                {block method="novel.list" name=list order=lastupdate num=$paginate.limit page=$paginate.current isover=1}
                {section loop=$list item=$loop}
                <div class="flex-wrp pt-finish-item">
                    <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
                        <img src="{$loop.novel.cover}" class="mr15" alt="{$loop.novel.name}">
                    </a>
                    <div class="flex-item flex-wrp flex-cell flex-between pt5">
                        <a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
                            <div class="size14 color7">{$loop.novel.name}</div>
                        </a>
                        <div class="size12 color5">
                            <a title="{$loop.author.name}" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">
                                <span class="size12 color5">{$loop.author.name}</span>
                            </a>|
                            <a title="{$loop.category.name}" href="{link=novel.category.list id=$loop.category.id key=$loop.category.key}">
                                <span class="size12 color5">{$loop.category.name}</span>
                            </a>
                        </div>
                        <div class="size12 compulsory-row-one lh130 color4">{$loop.novel.intro|showIntroLine}</div>
                        <div class="flex-wrp flex-between">
                            <div class="flex-wrp flex-align-center color5 size12">{$loop.data.allvisit}次点击</div>
                            <div class="pt-finish-label">{$loop.data.words}万字</div>
                        </div>
                    </div>
                </div>
                {/section}
            </div>
        </div>

        {if $paginate.total > 1}
        <div class="flex-wrp flex-between bg-white ptb15 plr15 mt10">
            {if $paginate.first != $paginate.current}
            <div class="flex-wrp flex-around flex-center pt-page4">
                <a title="首页" href="{link=novel.over.index page=$paginate.first}">
                    <span class="size14 color2">首页</span>
                </a>
            </div>
            {/if}
            {if $paginate.prev}
            <div class="flex-wrp flex-around flex-center pt-page4">
                <a title="上一页" href="{link=novel.over.index page=$paginate.prev}">
                    <span class="size14 color2">上一页</span>
                </a>
            </div>
            {/if}
            {if $paginate.next}
            <div class="flex-wrp flex-around flex-center pt-page4">
                <a title="下一页" href="{link=novel.over.index page=$paginate.next}">
                    <span class="size14 color2">下一页</span>
                </a>
            </div>
            {/if}
            {if $paginate.last != $paginate.current}
            <div class="flex-wrp flex-around flex-center pt-page4">
                <a title="尾页" href="{link=novel.over.index page=$paginate.last}">
                    <span class="size14 color2">尾页</span>
                </a>
            </div>
            {/if}
        </div>
        {/if}
    </div>


    <!-- 底部版权 -->
    {include file="/system/footer"}
    <!-- 底部按钮 -->
    {include file="/system/footerbutton"}
	<!-- js -->
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/index.js"></script>
</body>
</html>