<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
    <style>.pt-pop-grade .pt-cont {bottom: .56rem;}</style>
</head>
<body>
	<!-- 头部 -->
	<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
		<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return" onclick="window.history.back();">
		<div class="size18 bold color37">{$novel.name}</div>
        <div>
            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/ellipsis.png" class="mr5 pt-ellipsis">
        </div>
        <!-- tip -->
        <div class="flex-wrp flex-cell flex-around pt5 pb5 pt-tip">
            <div class="block color1 text-center lh100 pt-tip-item btn-mark" style="width: 100%;">加入书架</div>
            <a href="{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" class="block color1 text-center lh100 pt-tip-item">书籍详情</a>
            <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
            <a href="{link=novel.search.index}" class="block color1 text-center pt-tip-item">搜索小说</a>
            <a href="{link=user.mark.index}" class="block color1 lh100 text-center pt-tip-item">我的书架</a>
        </div>
	</div>
    <div class="flex-wrp bg-white" style="padding: 0.15rem">
        <h1 class="lh100 size18 color7">
            <a title="{$novel.name}" href="{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" class="color7">{$novel.name}</a>
            {if $novel.is_over}
            这本书您已经读完了！
            {else}
            所有更新您都读完了！
            {/if}
        </h1>
    </div>
    <div class="w100 mt10 mb10 ptb25 bg-white flex-wrp">
        <div class="w33 flex-wrp flex-cell flex-center pt-tj-btn">
            <div class="pt-tj-icon"></div>
            <div class="size14 mt10 mb5">我要推荐</div>
            <div class="size12 color92"><span class="num-vote">{$data.vote}</span>人推荐</div>
        </div>
        <div class="w33 flex-wrp flex-cell flex-center pt-star-btn">
            <div class="pt-star-icon"></div>
            <div class="size14 mt10 mb5">我来评分</div>
            <div class="size12 color92"><span class="num-star-people">{$data.star_num}</span>人评分</div>
        </div>
        <div class="w33 flex-wrp flex-cell flex-center btn-mark">
            <div class="pt-mark-icon"></div>
            <div class="size14 mt10 mb5 mark-title">{$ismark|default='加入收藏','取消收藏'}</div>
            <div class="size12 color92"><span class="num-mark">{$data.mark}</span>人收藏</div>
        </div>
    </div>
	<!-- 猜你喜欢 -->
	<div class="w100 bg-white lh100 pt-recomment mt15">
		<div class="size14 color7 bold pt-recomment-title">热门推荐</div>
		<div class="pt-recomment-cont">
            {block method="novel.list" name=list order=weekvisit num=9}
            {section loop=$list item=$loop}
			<div class="flex-wrp pt-recomment-item">
                <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
                    <img src="{$loop.novel.cover}" class="mr15" alt="{$loop.novel.name}">
                </a>
				<div class="flex-item pt5">
					<div class="flex-wrp flex-between">
                        <div class="size14 color7">
                            <a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}">{$loop.novel.name}</a>
                        </div>
						<div class="color2 size14">{$loop.data.mark} <span class="size12">人在追</span></div>
					</div>
					<div class="size12 compulsory-row mb10 mt10 lh130 color4">
                        {$loop.novel.intro|showIntroLine}
					</div>
					<div class="flex-wrp flex-between">
                        <div class="color5 size12"><a href="">{$loop.author.name}</a></div>
						<div class="pt-recomment-label"><a title="{$loop.category.name}" href="{link=novel.category.list categoryid=$loop.category.id key=$loop.category.key}">{$loop.category.name}</a></div>
					</div>
				</div>
			</div>
            {/section}
		</div>
	</div>
    <!-- 我要评分 -->
    <div class="pt-pop-grade pt-star-box" data-type="star">
        <div class="pt-cont">
            <div class="flex-wrp flex-between flex-align-center plr25">
                <div class="pt-close"></div>
                <div class="flex-wrp flex-center">
                    <div class="size18 bold colord5">—</div>
                    <div class="bold size18 color2 plr15">我要评分</div>
                    <div class="size18 bold colord5">—</div>
                </div>
                <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/read_pop_catalogue_close.png" class="pt-close">
            </div>
            <div class="flex-wrp flex-flow-row flex-around plr10 mt30">
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="1"><span class="size14">1</span>分</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="2"><span class="size14">2</span>分</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="3"><span class="size14">3</span>分</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="4"><span class="size14">4</span>分</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="5"><span class="size14">5</span>分</div>
            </div>
            <div class="flex-wrp flex-center size14 color1 pt-submit">确认提交</div>
        </div>
    </div>
    <!-- 成功评分、已添加到书架、已推荐 -->

    <div class="pt-pop-grade pt-tj-box" data-type="vote">
        <div class="pt-cont">
            <div class="flex-wrp flex-between flex-align-center plr25">
                <div class="pt-close"></div>
                <div class="flex-wrp flex-center">
                    <div class="size18 bold colord5">—</div>
                    <div class="bold size18 color2 plr15">我要推荐</div>
                    <div class="size18 bold colord5">—</div>
                </div>
                <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/read_pop_catalogue_close.png" class="pt-close">
            </div>
            <div class="flex-wrp flex-flow-row flex-around plr10 mt30">
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="1"><span class="size14">1</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="2"><span class="size14">2</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="3"><span class="size14">3</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="4"><span class="size14">4</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="5"><span class="size14">5</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="6"><span class="size14">6</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="7"><span class="size14">7</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="8"><span class="size14">8</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="9"><span class="size14">9</span>票</div>
                <div class="flex-wrp flex-center color62 size12 mb15 pt-square" data-value="all">所有</div>
            </div>
            <div class="flex-wrp flex-center size14 color1 pt-submit">确认提交</div>
        </div>
    </div>
    <!-- 底部版权 -->
    {include file="/system/footer"}
    <!-- 底部按钮 -->
    {include file="/system/footerbutton"}
    <script>var __ADD_STAR='{link=user.star.add}',__NOVEL_ID='{$novel.id}',__NOVEL_NAME='{$novel.name}',__ADD_MARK='{link=user.mark.add}',__DEL_MARK='{link=user.mark.del}',__ADD_VOTE='{link=user.vote.add}',__RATING_COMMENT='{link=novel.comment.rating}',__ADD_COMMENT='{link=novel.comment.add}';</script>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/layer/mobile/layer.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/novel.js"></script>
</body>
</html>