<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>账户绑定 - 用户中心 - {$kx.config.sitename}</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/global.css"/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/style.css"/>
</head>
<body>
	<!-- 头部 -->
    {include file="/system/header"}

	<!-- 内容 -->
	<div class="pt-content">
		<!-- 面包屑 -->
		<div class="pt-crumb">
			<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/images/crumb_icon.png" class="pt-crumb-icon">
			<span class="color5">
                <a href="{$kx.config.siteurl}">{$kx.config.sitename}</a> > <a href="{link=user.index.index}" class="color5">用户中心</a> > <a href="{link=user.info.bind}">账户绑定</a>
            </span>
		</div>


		<!-- 一楼 -->
		<div class="pt-floor1">
            {include file="/system/userleft"}
			<div class="relative pt-rank">
				<div class="pt-rank-head">
					<span class="size18 color2 mr10">账户绑定</span>
				</div>
                <div class="pt-list-content">
                    {if $kx.config.oauth.power}
                    <ul class="oauth">
                        <li>
                            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/images/qq.png">
                            {block method=user.isbind type=qq userid=$userinfo.id name=isbind}
                            {if $isbind}
                            <span class="size18 bold color3 block">已绑定</span>
                            <a href="{link=user.auth.unbind type=qq}">取消绑定</a>
                            {else}
                            <span class="size18 bold color3 block">未绑定</span>
                            <a href="{link=user.auth.third type=qq}">前往绑定</a>
                            {/if}
                        </li><li>
                            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/images/wb.png">
                            {block method=user.isbind type=weibo userid=$userinfo.id name=isbind}
                            {if $isbind}
                            <span class="size18 bold color3 block">已绑定</span>
                            <a href="{link=user.auth.unbind type=weibo}">取消绑定</a>
                            {else}
                            <span class="size18 bold color3 block">未绑定</span>
                            <a href="{link=user.auth.third type=weibo}">前往绑定</a>
                            {/if}
                        </li>
                        <li>
                            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/images/wx.png">
                            {block method=user.isbind type=weixin userid=$userinfo.id name=isbind}
                            {if $isbind}
                            <span class="size18 bold color3 block">已绑定</span>
                            <a href="{link=user.auth.unbind type=weixin}">取消绑定</a>
                            {else}
                            <span class="size18 bold color3 block">未绑定</span>
                            <a href="{link=user.auth.third type=weixin}">前往绑定</a>
                            {/if}
                        </li>
                    </ul>
                    {/if}
                </div>

			</div>
		</div>
	</div>

	<!-- 底部版权-->
    {include file="/system/footer"}

	<!-- js-->
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/js/rankdetail.js"></script>
</body>
</html>