<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Mark - UserCP - {$kx.config.sitename}</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/global.css"/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/style.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/js/jquery-3.3.1.js"></script>
</head>
<body>
	<!-- 头部 -->
    {include file="/system/header"}

	<!-- 内容 -->
	<div class="pt-content">
		<!-- 面包屑 -->
		<div class="pt-crumb">
			<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/images/crumb_icon.png" class="pt-crumb-icon">
			<span class="color5">
                <a href="{$kx.config.siteurl}">{$kx.config.sitename}</a> > <a href="{link=user.index.index}" class="color5">UserCP</a> > <a href="{link=user.mark.index}">Mark</a>
            </span>
		</div>


		<!-- 一楼 -->
		<div class="pt-floor1">
            {include file="/system/userleft"}
			<!-- 云书架 -->
			<div class="relative pt-rank">
                {block method=mark.list userid=$userinfo.id name=list order=$order}
				<!-- 书架title -->
				<div class="pt-rank-head">
					<span class="size18 color2 mr10">Mark</span>
					<span class="size12 color4">（<span class="color2">{$list|count}</span>）</span>
					<div class="relative fr">
						<span class="color4">Order:</span>
						<span class="pt-select">
							<span class="pt-select-text">{=$order=='read'?'LastRead':'LastMark'}</span>
							<span class="pt-triangle"></span>
						</span>
						<div class="pt-select-cont">
							<span><a href="{link='' order=update}">Update</a></span>
							<span><a href="{link='' order=read}">LastRead</a></span>
							<span><a href="{link='' order=add}">LastMark</a></span>
						</div>
					</div>
				</div>
				<!-- 分类详情 -->
                {loop}
				<div class="pt-rank-detail">
                    <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="fl">
                        <img src="{$loop.novel.cover}">
                    </a>
                    <div class="fl pt-rank-detail-middle">
                        <div class="fl w100 lh100">
							<span class="fl mr60">
								<a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="size18 color2">{$loop.novel.name}</a>
							</span>
                            <span class="fl color7">
								<span class="mr30">Author：<a href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a> </span>
							</span>
                            {if $loop.markinfo.newnum>0}<span class="fr color5"><b class="color2">{$loop.markinfo.newnum}</b> Chapter Unread</span>{/if}
                        </div>
                        <div class="compulsory-row fl w100 color5 desc" style="margin-bottom:5px;margin-top:8px;">
                            {$loop.novel.intro|showIntroLine}
                        </div>
                        <div class="fl lh100 w100" style="margin-bottom:7px;">
                            <span>
                                Update：
                                <a href="{link=novel.chapter.read pinyin=$loop.novel.pinyin novelid=$loop.novel.id chapterid=$loop.last.id}">
                                    <span class="color2 mr20">{$loop.last.name}</span>
                                </a>
                            </span>
                            <span class="color0 size12">{$loop.last.time|date="Y-m-d H:i:s"}</span>
                        </div>
                        <div class="fl lh100 w100">
                            <span>
                                Mark：
                                {if ($loop.markinfo.chapterid)}
                                <a href="{link=novel.chapter.read pinyin=$loop.novel.pinyin novelid=$loop.novel.id chapterid=$loop.markinfo.chapterid}">
                                    <span class="color2 mr20">{$loop.markinfo.name}</span>
                                </a>
                                {else}
                                <span class="color2">No Mark</span>
                                {/if}
                            </span>
                        </div>
                    </div>
                    <div class="fr mr30">
                        <a href="{link=novel.chapter.read pinyin=$loop.novel.pinyin novelid=$loop.novel.id chapterid=$loop.markinfo.nextid}" class="mb20 color2 border-red pt-btn read">Continue reading</a>
                        <a href="{link=user.mark.del novelid=$loop.novel.id}" class="border-c9 color4 pt-btn mark">Remove Mark</a>
                    </div>
				</div>
                {/loop}

				<!-- 分页 -->
				<!-- <div class="pt-pages">
					<div class="pt30 color5">
						<span class="mr15"><</span>
						<span class="pt-pages-select">1</span>
						<span class="border-red color2">2</span>
						<span>3</span>
						<span>4</span>
						<span>5</span>
						<span>...</span>
						<span>81</span>
						<span>></span>
					</div>
				</div> -->
			</div>
		</div>
	</div>

	<!-- 底部版权-->
    {include file="/system/footer"}

	<!-- js-->
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/js/rankdetail.js"></script>
</body>
</html>