<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>设置用户名 - {$kx.config.sitename}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/login.css"/>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<!-- 头部 -->
<div class="w100 pt-head-bg" style="background:none;margin-top: 10px;">
    <div class="pt-head">
        <img src="https://qidian.gtimg.com/qd/images/logo_2x.78ab6.png" class="pt-logo" title="{$kx.config.sitename}">
        <span class="lh100 size16 fr" style="margin-top: 50px;">我要免费看小说! 我要 <a title="注册" href="{link=user.auth.register}" class="color2">免费注册</a>，<a title="注册" href="{link=user.auth.login}" class="color2">登录已有账号</a></span>
    </div>
</div>

<!-- 导航栏 -->
<div class="pt-navbg" style="background:none;">
    <div class="pt-nav" style="background-color: #FF5555;height: 76px">
        <div class="text-center size26 color1 pt20">设置用户名</div>
    </div>
</div>

<!-- 内容 -->
<div class="pt-content" style="padding-top: 40px;">
    <div class="pt-login">
        <div class="color4 pt-login-title">
            <a class="cursor size16 pb10 pt-btn2 pt-select mr10">快捷登录</a>
        </div>
        <!-- 账号登录 -->
        <form class="pt-accountlogin clearfix" method="post" action="{link=user.auth.register}">
            <input type="hidden" name="oauth[type]" value="{$oauth.type}">
            <input type="hidden" name="oauth[openid]" value="{$oauth.openid}">
            <span class="fr color62 mt30">请输入您要申请的账号</span>
            <input type="text" name="username" placeholder="请输入您要设置的账号" class="pt-login-account" style="margin-top: 0;">
            <span class="fr color62 mt10">请输入绑定邮箱</span>
            <input type="email" name="email" placeholder="请输入绑定邮箱" class="pt-login-password" style="margin-top: 0;">
            <span class="fr color62 mt10">请输入密码</span>
            <input type="password" name="password" placeholder="请输入密码" class="pt-login-password" style="margin-top: 0;">
            <span class="fr color62 mt10">请确认密码</span>
            <input type="password" name="repassword" placeholder="请重复一次你的的密码" class="pt-login-password" style="margin-top: 0;">
            <button class="cursor pt-login-btn">确认提交</button>
            <div class="size12 color4 mb35">
                    <span class="fl text-center pt-select-box">
                        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/images/true.png" class="">
                    </span>
                <span class="fl">我同意<a href="{link=page.detail key=agreement}">用户协议</a></span>
                <div class="fr">
                    <a href="{link=user.auth.login}" class="color4">已有账号</a>
                </div>
            </div>
        </form>
    </div>

</div>


<!-- 底部版权-->
<div class="pt-copyright" style="margin-top: 0;margin-bottom: 0;">
    <div class="color4 footer-info">Copyright © 2009 - 2019 <a href="{$kx.config.siteurl}" target="_blank">{$kx.config.sitename}</a>. All Rights Reserved . 版权所有{$kx.config.sitename}</div>
    <div class="color4 footer-info">Power by <a href="http://www.ptcms.com" target="_blank">PT聚合小说搜索聚合程序 {$kx.PRO_VERSION} Build{$kx.PRO_TIME}</a>，模版设计：<a href="http://www.pakey.net" target="_blank">Pakey</a>，<a href="http://www.miitbeian.gov.cn/" target="_blank" rel="nofollow">{$kx.config.beian}</a></div>
</div>
<div class="none">
    {$kx.config.tongji.pc}
</div>
<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/js/jquery-3.3.1.js"></script>
<script>
    window.onload = function () {
        // 同意用户协议选中框
        $('.pt-select-box').click(function () {
            $('img', this).toggle()
        })
    }
</script>
</body>
</html>