<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/global.css"/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/css/style.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinpc1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
	<!-- 导航栏 -->
    {include file="/system/header"}
	<!-- 内容 -->
	<div class="pt-content mt10">
		<!-- 一楼 -->
		<div class="pt-floor1 clearfix">
			<!-- 分类 -->
			<div class="pt-rank" style="float: left;">
                {block method=booklist.count userid=$userinfo.id name=count tags=$kx.get.tagid}
                {block method="pagination" name="paginate" page=$page limit=$pageSize count=$count maxpage=50 section=3}
                {block method=booklist.list name=list tags=$kx.get.tagid num=$paginate.limit page=$paginate.current}
                <div class="pt-booklist-head">
                    <a href="{link=index}">
                        {block method=booklist.count userid=$userinfo.id name=total}
                        <span class="size14 color1 bg-red plr20 ptb5" style="border-radius:2px;">全部 ({$total})</span>
                    </a>
                    <div class="tags inline-block">
                        <span class="size14 color3 ml20 ml15">热门标签：</span>
                        {block method=booklist.hottags name=hottags}
                        <ul>
                            {loop=hottags}
                            <li><a href="{link=index tagid=$loop.id}" class="color5">{$loop.name}<!--({$loop.num})--></a></li>
                            {/loop}
                        </ul>
                    </div>
                </div>
                <ul class="pt-booklist" style="min-height: 600px;">
                    {loop}
                    <li class="pt-booklist-detail">
                        <a href="{link=detail booklistid=$loop.id}">
                            <img class="fl pt-booklist-cover" src="{$loop.cover}" alt="{$loop.title}">
                            <div class="fl pt-booklist-info">
                                <span class="fl mr60 size24 color3 bold">{$loop.title}</span>
                                <span class="mr30 fl color62 w100">
                                    <span class="inline-block" style="width: 130px;overflow: hidden">{$loop.user.name}</span>
                                    <span class="fr color0">创建于 {$loop.create_time|date="Y-m-d H:i"}</span>
                                </span>
                                <div class="compulsory-row fl w100 color92 desc" style="margin-bottom:5px;margin-top:8px;">
                                    {$loop.intro|showIntroLine}
                                </div>
                                <div class="stat">
                                    书籍 <span class="color2">{$loop.num_novel}</span><span class="color3 plr5">/</span>
                                    历史浏览 <span class="color2">{$loop.num_allvisit}</span><span class="color3 plr5">/</span>
                                    收藏 <span class="color2">{$loop.num_mark}</span>
                                </div>
                            </div>
                        </a>
                    </li>
                    {/loop}
                </ul>
                <div class="clearfix"></div>
                <!-- 分页 -->
                <div class="pt-pages mt15">
                    <div class="pt30 color5">
                        {if $paginate.prev}
                        <a href="{link=booklist.booklist.index page=$paginate.prev tagid=$kx.get.tagid}"><span><</span></a>
                        {else}
                        <span class="disable"><</span>
                        {/if}
                        {loop=paginate.items}
                        <a href="{link=booklist.booklist.index page=$loop.num tagid=$kx.get.tagid}">
                            <span class="{$loop.status|default='','pt-pages-select'}">{$loop.num}</span>
                        </a>
                        {/loop}
                        {if $paginate.next}
                        <a href="{link=booklist.booklist.index page=$paginate.next tagid=$kx.get.tagid}"><span>></span></a>
                        {else}
                        <span class="disable">></span>
                        {/if}
                    </div>
                </div>
            </div>
			<div class="w240 fr">
                <!-- 周榜、月榜 -->
                <div class="pt-sexselect">
                    <div class="pt-sexselect-title border-b"><span class="fl pt-sexselect-title-icon"></span>最新书单</div>
                    <ul class="pt-sexselect-list">
                        {block method=booklist.list name=list num=10 order='add' sort='desc'}
                        {section loop=$list item=$loop}
                        <li>
                            <span class="{=$i.index<3?'bg-red':'bg-ccc'} pt-sexselect-square">{=$i.index + 1}</span>
                            <a class="color5" href="{link=detail booklistid=$loop.id}" title="{$loop.title}">{$loop.title}</a>
                            <a title="{$loop.author.name}" class="color3 fr">{$loop.user.name}</a>
                        </li>
                        {/section}
                    </ul>
                </div>
                <div class="pt-sexselect">
                    <div class="size18 color4 w100  border-b" style="padding-bottom:8px;">
                        <span class="pt-sexselect-man pt-sexselect-active cursor" style="margin-left: 60px;">点击</span>
                        <span class="pt-sexselect-woman cursor">收藏</span>
                    </div>
                    <ul class="pt-sexselect-list">
                        {block method=booklist.list name=list num=10 order='allvisit' sort='desc'}
                        {section loop=$list item=$loop}
                        <li class="">
                            <span class="{=$i.index<3?'bg-red':'bg-ccc'} pt-sexselect-square">{=$i.index + 1}</span>
                            <a class="color5" href="{link=detail booklistid=$loop.id}" title="{$loop.title}">{$loop.title}1</a>
                            <a title="{$loop.author.name}" class="color3 fr">{$loop.user.name}</a>
                        </li>
                        {/section}
                    </ul>
                    <ul class="pt-sexselect-list none">
                        {block method=booklist.list name=list num=10 order='mark' sort='desc'}
                        {section loop=$list item=$loop}
                        <li>
                            <span class="{=$i.index<3?'bg-red':'bg-ccc'} pt-sexselect-square">{=$i.index + 1}</span>
                            <a class="color5" href="{link=detail booklistid=$loop.id}" title="{$loop.title}">{$loop.title}2</a>
                            <a title="{$loop.author.name}" class="color3 fr">{$loop.user.name}</a>
                        </li>
                        {/section}
                    </ul>
                </div>
                <!-- 新书推荐 -->
                <div class="fr pt-new-recomment">
                    <div class="pt-new-recomment-title">新书推荐</div>
                    <ul class="pt-new-recomment-list">
                        {block method="recommend" name=list recommendid=1 num=10}
                        {loop=$list}
                        <li>
                            <a title="{$loop.data.category.name}" class="color3" href="{link=novel.category.list categoryid=$loop.data.category.id key=$loop.data.category.key}">[{$loop.data.category.name}]</a>
                            <a href="{link=novel.novel.index novelid=$loop.data.novel.id pinyin=$loop.data.novel.pinyin}" class="color4 pt-text" title="{$loop.data.novel.name}">{$loop.data.novel.name}</a>
                        </li>
                        {/loop}
                    </ul>
                </div>
            </div>
		</div>
	</div>
	<!-- 底部版权-->
    {include file="/system/footer"}
    <script>
        $('.pt-sexselect div span').on('click',function(){
            $(this).addClass('pt-sexselect-active').siblings().removeClass('pt-sexselect-active');
            $(this).parent().parent().find('ul').eq($(this).index()).removeClass('none').siblings('.pt-sexselect-list').addClass('none');
        })
    </script>
</body>
</html>