<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/global.css"/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/style.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
	<!-- 头部 -->
    {include file="/system/header"}
	<!-- 内容 -->
	<div class="pt-content mt10">
		<!-- 一楼 -->
		<div class="pt-floor1">
			<div class="pt-list">
				<!-- 人气榜单 -->
                <div class="fr pt-toplist">
                    <div class="border-b size18 color8 pb10 pt-toplist-title">人气榜单</div>
                    <div class="pt-toplist-item">
                        {block method="rank.out" name=list}
                        {loop}
                        <a title="{$loop.name}" href="{link=novel.rank.list key=$loop.key}"><span class="mr10">·</span>{$loop.name}</a>
                        {/loop}
                    </div>
                </div>
                <!-- 站内榜单 -->
                <div class="fr pt-sortlist">
                    <div class="border-b size18 color8 pb10 pt-sortlist-title">站内榜单</div>
                    {block method="rank.list" name=list}
                    {loop=list}
                    <div class="pt-sortlist-item fl" style="width:50%">
                        <a title="{$loop.name}" class="color8 fl" href="{link=novel.rank.list key=$loop.key}">{$loop.name}</a>
                    </div>
                    {/loop}
                </div>
			</div>
			<!-- 分类 -->
			<div class="relative pt-rank">
                {block method="pagination" name="paginate" page=$page limit=$pageSize count=$category.num maxpage=50 section=3}
                <!-- 选择分类 -->
				<div class="pt-rank-head">
					<span class="size18 color2 mr10">{$category.name}</span>
					<span class="size12 color4">共 <span class="color2">{$category.num}</span> 本</span>
				</div>
				<!-- 分类详情 -->
				<div class="pt-sort-detail">
					<div class="color7 border-e9 pt-sortdetail-title">
						<span class="fl pt-sortdetail-item1">类别</span>
						<span class="fl pt-sortdetail-item2">书名</span>
						<span class="fl pt-sortdetail-item3">最新章节</span>
						<span class="fl pt-sortdetail-item4">作者</span>
						<span class="fl pt-sortdetail-item5">更新时间</span>
					</div>
                    {block method="novel.list" name=list category=$category.id order=weekvisit num=$paginate.limit page=$paginate.current}
                    {section loop=$list item=$loop}
					<div class="color7 pt-sortdetail-title">
						<span class="fl compulsory-row-one pt-sortdetail-item1"><a title="{$loop.category.name}" href="{link=novel.category.list id=$loop.category.id key=$loop.category.key}">{$loop.category.name}</a></span>
						<span class="fl compulsory-row-one pt-sortdetail-item2"><a tabindex="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}">{$loop.novel.name}</a></span>
						<span class="fl compulsory-row-one pt-sortdetail-item3">{if $loop.last.id}<a title="{$loop.last.name}" href="{link=novel.chapter.read novelid=$loop.novel.id pinyin=$loop.novel.pinyin chapterid=$loop.last.id}">{$loop.last.name}</a>{else}{$loop.last.name}{/if}</span>
						<span class="fl compulsory-row-one pt-sortdetail-item4" title=">{$loop.author.name}"><a title="{$loop.author.name}" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a></span>
						<span class="fl compulsory-row-one pt-sortdetail-item5">{$loop.last.time|date="m-d H:i"}</span>
					</div>
                    {/section}
                </div>
				<!-- 分页 -->
                <div class="pt-pages">
                    <div class="pt30 color5">
                        {if $paginate.prev}
                        <a href="{link=novel.category.list categoryid=$category.id key=$category.key page=$paginate.prev}"><span><</span></a>
                        {else}
                        <span class="disable"><</span>
                        {/if}
                        {loop=paginate.items}
                        <a href="{link=novel.category.list categoryid=$category.id key=$category.key page=$loop.num}">
                            <span class="{$loop.status|default='','pt-pages-select'}">{$loop.num}</span>
                        </a>
                        {/loop}
                        {if $paginate.next}
                        <a href="{link=novel.category.list categoryid=$category.id key=$category.key page=$paginate.next}"><span>></span></a>
                        {else}
                        <span class="disable">></span>
                        {/if}
                    </div>
                </div>
			</div>	
		</div>
	</div>
	
	<!-- 底部版权-->
    {include file="/system/footer"}
</body>
</html>