<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/style.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<!-- 头部 -->
{include file="/system/header"}

<!-- 内容 -->
<div class="pt-content mt10">
    <!-- 一楼 -->
    <div class="pt-floor1">
        <div class="pt-list">
            <!-- 人气榜单 -->
            <div class="fr pt-toplist">
                <div class="border-b size18 color8 pb10 pt-toplist-title f_bold">人气榜单</div>
                <div class="pt-toplist-item">
                    {block method="rank.out" name=list}
                    {loop}
                    <a title="{$loop.name}" href="{link=novel.rank.list key=$loop.key}"><span class="mr10">·</span>{$loop.name}</a>
                    {/loop}
                </div>
            </div>
            <!-- 站内榜单 -->
            <div class="fr pt-sortlist">
                <div class="border-b size18 color8 pb10 pt-sortlist-title f_bold">站内榜单</div>
                {block method="rank.list" name=list}
                {loop=list}
                <div class="pt-sortlist-item fl" style="width:50%">
                    <a title="{$loop.name}" class="color8 fl" href="{link=novel.rank.list key=$loop.key}">{$loop.name}</a>
                </div>
                {/loop}
            </div>
        </div>
        <!-- 排名 -->
        <div class="pt-rank pt-rank-padding">
            {block method="rank.list" name=list}
            {loop=list}
            <div class="pt-rank-cont">
                <div class="pt-rank-cont-title">
                    <span class="fl pt-rank-cont-title-icon"></span>
                    <a title="{$loop.name}" class="size18 color7 f_bold">{$loop.name}</a>
                    <a title="{$loop.name}" class="size18 color4 fr more" href="{link=novel.rank.list key=$loop.key}">更多+</a>
                </div>
                <ul class="mt15">
                    {block method="novel.list" name=list order=$loop.key num=10}
                    {section loop=$list item=$loop}
                    <li>
                        <span class="{=$i.index<3?'bg-red':'bg-ccc'} fl pt-sexselect-square">{=$i.index + 1}</span>
                        <a class="color5" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" title="{$loop.novel.name}">{$loop.novel.name}</a>
                        <a title="{$loop.author.name}" class="color3 fr" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a>
                    </li>
                    {/section}
                </ul>
            </div>
            {/loop}
        </div>
    </div>
    <!-- 友情链接 -->
</div>

<!-- 底部版权-->
{include file="/system/footer"}
</body>
</html>