<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/style.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<!-- 导航栏 -->
{include file="/system/header"}
<!-- 内容 -->
<div class="pt-content">
    <!-- 面包屑 -->
    <div class="pt-crumb">
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/images/crumb_icon.png" class="pt-crumb-icon">
        <span class="color5"><span class="color5"><a title="{$kx.config.sitename}" href="{$kx.config.siteurl}">{$kx.config.sitename}</a> > <a title="{$category.name}" href="{link=novel.category.list categoryid=$category.id key=$category.key}" class="color5">{$category.name}</a> > <a title="{$novel.name}" href="{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" class="color5">{$novel.name}</a></span> > 阅读尾页</span>
    </div>
    <!-- 阅读内容 -->
    <div class="pt-read-cont">
        <div class="pt-read-title">
            <h1 class="lh100 size26 color7 mb20">
                <a title="{$novel.name}" href="{link=novel.novel.index novelid=$novel.id pinyin=$novel.pinyin}" class="color7">{$novel.name}</a>
                {if $novel.is_over}
                这本书您已经读完了！
                {else}
                所有更新您都读完了！
                {/if}
            </h1>
        </div>
        <div class="size16 color5 pt-read-text">
            <ul class="pt-featured-list clearfix ml10" style="margin-left: 100px;">
                {block method="novel.list" name=list order=weekvisit num=9}
                {loop=$list}
                <li>
                    <a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}"><img src="{$loop.novel.cover}" alt="{$loop.novel.name}"></a>
                    <div class="pt-featured-list-cont">
                        <div><a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="size16 color7 compulsory-row-one">{$loop.novel.name}</a></div>
                        <div class="size14 color8" style="margin-top:5px">作者：<a title="{$loop.author.name}" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}">{$loop.author.name}</a></div>
                        <div class="pt-featured-list-cont-intro compulsory-row-four size12 color4">{$loop.novel.intro|showIntroLine|truncate=50}</div>
                        <div class="size14 color7"><a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">前往阅读 >></a></div>
                    </div>
                </li>
                {/loop}
            </ul>
        </div>
    </div>
    <!-- 底部按钮 -->

</div>
<!-- 底部版权-->
{include file="/system/footer"}
<!-- js -->
</body>
</html>