<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/style.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
    <style>
        .pt-floor1 ul{
            padding-top: 25px;
        }
        .pt-floor1 li{
            width: 560px;
            height: 260px;
            margin-left: 26px;
            display: inline-block;
            margin-bottom: 50px;
        }
        .pt-floor1 li img{
            width: 560px;
            height: 200px;
        }
        .pt-floor1 li .allvisit{
            float: right;
            padding-left: 25px;
            background: url('https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/images/hot.png') no-repeat;
        }
    </style>
</head>
<body>
{include file="/system/header"}
<div class="pt-content mt10">
    <div class="pt-floor1 bg-white"  style="min-height: 600px;">
        <ul>
            {block method=special.count userid=$userinfo.id name=count}
            {block method="pagination" name="paginate" page=$page limit=$pageSize count=$count maxpage=50 section=3}
            {block method=special.list num=$paginate.limit page=$paginate.current name=list}
            {loop}
            <li>
                <a href="{link=detail specialid=$loop.id}" title="{$loop.intro}">
                    <img src="{$loop.cover}" alt="{$loop.intro}">
                    <span class="fl size16 bold color32 compulsory-row-one" style="width: 80%">{$loop.title}</span>
                    <span class="allvisit">{$loop.num_allvisit}</span>
                </a>
            </li>
            {/loop}
        </ul>
        {if empty($list)}
        <div class="text-center size16">暂无数据</div>
        {/if}
        {if $paginate.total>1}
        <div class="pt-pages">
            <div class="pt30 color5">
                {if $paginate.prev}
                <a href="{link=novel.over.index page=$paginate.prev}"><span><</span></a>
                {else}
                <span class="disable"><</span>
                {/if}
                {loop=paginate.items}
                <a href="{link=novel.over.index page=$loop.num}">
                    <span class="{$loop.status|default='','pt-pages-select'}">{$loop.num}</span>
                </a>
                {/loop}
                {if $paginate.next}
                <a href="{link=novel.over.index page=$paginate.next}"><span>></span></a>
                {else}
                <span class="disable">></span>
                {/if}
            </div>
        </div>
        {/if}
    </div>
    {include file="/system/footer"}
</body>
</html>