<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>我的书单 - {$kx.config.sitename}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
    <style>
        .pt-labs .active{
            color: #f55;
        }
        .pt-labs .active div{
            width: 24px;
            height: 3px;
            background-color: #f55;
            position: absolute;
            margin-top: 5px;
            margin-left: 9px;
        }
        .pt-popular-cont{
            display: none;
        }
        .pt-popular-cont.active{
            display: block;
        }
    </style>
</head>
<body>
	<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
		<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return" onclick="window.history.back();">
		<div class="size14 bold color89 pt-labs">
            <div data-type="create" class="inline-block active mr30">已发布 <div></div></div>
            <div data-type="mark" class="inline-block">收藏夹 <div></div></div>
        </div>
        <div>
            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/ellipsis.png" class="mr5 pt-ellipsis">
        </div>
        <div class="pt5 pb5 pt-tip">
            <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
            <a href="{link=user.booklist.detail}" class="block color1 text-center pt-tip-item" title="{$novel.name}">创建书单</a>
        </div>
	</div>
    <div type="create" class="pt-popular-cont active">
        {block method=booklist.list userid=$userinfo.id name=list type=create status=all}
        {section loop=$list item=$loop}
        <a href="{link=detail id=$loop.id}">
            <div class="flex-wrp pt-popular-item">
                <img src="{$loop.cover}" class="mr15" alt="{$loop.title}">
                <div class="flex-item pt5">
                    <div class="flex-wrp flex-between">
                        <div class="size14">
                            <span class="color7">{$loop.title}</span>
                        </div>
                    </div>
                    <div class="size12 compulsory-row mb10 mt10 lh130 color4">
                        {$loop.intro|showIntroLine}
                    </div>
                    <div class="size12">
                        书籍 <span class="color2 mr5">{$loop.num_novel}</span><span class="color3 mr5">/</span>
                        浏览 <span class="color2 mr5">{$loop.num_allvisit}</span><span class="color3 mr5">/</span>
                        收藏 <span class="color2">{$loop.num_mark}</span>
                    </div>
                </div>
            </div>
        </a>
        {/section}
    </div>
    <div type="mark" class="pt-popular-cont">
        {block method=booklist.list userid=$userinfo.id name=list type=mark status=all}
        {section loop=$list item=$loop}
        <a href="{link=booklist.booklist.detail id=$loop.id}">
            <div class="flex-wrp pt-popular-item">
                <img src="{$loop.cover}" class="mr15" alt="{$loop.title}">
                <div class="flex-item pt5">
                    <div class="flex-wrp flex-between">
                        <div class="size14">
                            <span class="color7">{$loop.title}</span>
                        </div>
                    </div>
                    <div class="size12 compulsory-row mb10 mt10 lh130 color4">
                        {$loop.intro|showIntroLine}
                    </div>
                    <div class="size12">
                        书籍 <span class="color2 mr5">{$loop.num_novel}</span><span class="color3 mr5">/</span>
                        浏览 <span class="color2 mr5">{$loop.num_allvisit}</span><span class="color3 mr5">/</span>
                        收藏 <span class="color2">{$loop.num_mark}</span>
                    </div>
                </div>
            </div>
        </a>
        {/section}
    </div>
    <!-- 底部版权 -->
    {include file="/system/footer"}
    <script>
        $('.pt-labs > div').click(function () {
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            var type = $(this).data('type');
            $('.pt-popular-cont[type!='+type+']').removeClass('active');
            $('.pt-popular-cont[type='+type+']').addClass('active');
        });
    </script>
</body>
</html>