<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
	<title>基础资料 - 用户中心 - {$kx.config.sitename}</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <style>
        select {
            border: none;
            -webkit-appearance: none;
            -webkit-tap-highlight-color: #fff;
            outline: 0;
            padding: 0 .1rem;
        }
    </style>
</head>
<body>
    <form method="post">
        <div class="w100 vh100">
            <div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
                <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return">
                <div class="size18 bold color37">编辑资料</div>
                <button type="submit" style="background:none;">保存</button>
            </div>
            <div class="bg-white mt10">
                <input type="hidden" name="avatar" value="{$userinfo.avatar}">
                <div class="flex-wrp flex-align-center flex-between plr15 ptb15 border-b">
                    <span class="size14 color7">ID</span>
                    <span class="size14 color4">{$userinfo.id}</span>
                </div>
                <div class="flex-wrp flex-align-center flex-between plr15 ptb15 border-b">
                    <span class="size14 color7">昵称</span>
                    <input class="size14 color4 text-right" type="text" name="nickname" value="{$userinfo.nickname}">
                </div>
                <div class="flex-wrp flex-align-center flex-between plr15 ptb15 border-b">
                    <span class="size14 color7">性别</span>
                    <select class="size14 color4" name="sex">
                        <option value="0">保密</option>
                        <option value="1">男</option>
                        <option value="2">女</option>
                    </select>
                </div>
                <div class="flex-wrp flex-align-center flex-between plr15 ptb15 border-b">
                    <span class="size14 color7">简介</span>
                    <textarea class="size14 color4 text-right" name="intro" cols="45" rows="3">{$userinfo.intro}</textarea>
                </div>
            </div>
        </div>
    </form>

    <!-- 底部版权 -->
    {include file="/system/footer"}
</body>
</html>