<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>用户注册 - {$kx.config.sitename}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<div class="w100 vh100 bg-white">
    <div class="w100 flex-wrp flex-align-center flex-between lh100 plr15 pt-register">
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return">
        <div class="size18 bold color37">设置用户名</div>

        <div>
            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/ellipsis.png" class="mr5 pt-ellipsis">
        </div>
        <div class="pt5 pb5 pt-tip">
            <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
            <a href="{link=novel.search.index}" class="block color1 text-center pt-tip-item">搜索小说</a>
            <a href="{link=user.index.index}" class="block color1 text-center pt-tip-item" rel="nofollow">个人中心</a>
        </div>
    </div>
    <form method="post" action="{link=user.auth.register}">
        <input type="hidden" name="oauth[type]" value="{$oauth.type}">
        <input type="hidden" name="oauth[openid]" value="{$oauth.openid}">
        <!-- 登录账号 -->
        <div class="pt-email-title">登录账号</div>
        <div class="flex-wrp flex-align-center pt-email">
            <input type="text" placeholder="请输入您的账号" class="size12 color9"  name="username">
        </div>


        <!-- 登录密码 -->
        <div class="pt-password-title">登录密码</div>
        <div class="flex-wrp flex-align-center pt-password">
            <input type="text" placeholder="请输入您的密码" class="size12 color9" name="password">
        </div>

        <!-- 确认密码 -->
        <div class="pt-confirm-password-title">确认密码</div>
        <div class="flex-wrp flex-align-center pt-confirm-password">
            <input type="text" placeholder="请重复一次你的的密码" class="size12 color9" name="repassword">
        </div>

        <!-- 登录按钮 -->
        <button class="pt-login-btn block">确认提交</button>
    </form>

</div>

<!-- 底部版权 -->
{include file="/system/footer"}

</body>
</html>