<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
    <style>

    </style>
</head>
<body>
	<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
		<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return" onclick="window.history.back();">
		<div class="size18 bold color37">专题详情</div>
        <div><img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/ellipsis.png" class="mr5 pt-ellipsis"></div>
        <div class="pt5 pb5 pt-tip">
        </div>
	</div>
    <div>
        <div class="plr15 bg-white pb30">
            <h3 class="color37">{$special.title} </h3>
            <div class="compulsory-row-three pt-bookdetail-intro size14 pt10">
               <span class="color62 bold">专题概述：</span>{$special.intro|showIntroLine}
            </div>
            <div class="stat size12 pt10">
                书籍 <span class="color2">{$special.num_novel}</span><span class="color3 plr5">/</span>
                浏览 <span class="color2">{$special.num_allvisit}</span>
                <span class="fr color92">{$special.create_time|date='Y-m-d H:i'}</span>
            </div>
        </div>
        <style>
            .pt-booklist-novels li{
                background-color: #fff;
            }
            .pt-booklist-novels li:first-child{
                border-top: 1px solid #eee;
            }
            .pt-booklist-novels li .pt-novel-cover{
                width: 110px;
                height: 150px;
            }
            .pt-novel-comment{
                height:63px;
                border:1px solid #E9E9E9;
            }
        </style>
        <ul class="pt-booklist-novels">
            {loop=$special.novels}
            <li class="pt-novels plr15 pb15">
                <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
                    <div class="flex-wrp pt-popular-item">
                        <img src="{$loop.novel.cover}" class="mr15" alt="{$loop.novel.name}">
                        <div class="flex-item pt5">
                            <div class="flex-wrp flex-between">
                                <div class="size14">
                                    <span class="color7">{$loop.novel.name}</span>
                                </div>
                                <span class="size12" style="float: right">评分 <span class="color2 size16 bold">{$loop.data.star}</span></span>

                            </div>
                            <div class="size12 pt5 bold">{$loop.author.name} / {$loop.category.name} / {=$loop.novel.is_over?'完结':'连载'}</div>
                            <div class="size12 pt5"><span class="color2">{$loop.data.allvisit}</span>人在读</div>
                        </div>
                    </div>
                </a>
                <div class="pt-novel-comment compulsory-row plr10 ptb10">{$loop.comment|showIntro}</div>
            </li>
            {/loop}
        </ul>
    </div>
</body>
{include file="/system/footer"}
<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/layer/mobile/layer.js"></script>
<script>
    $('.pt-novel-comment').click(function(){
        layer.open({
            type: 1,
            content:'<div class="plr5">'+this.innerHTML+'</div>',
            anim: 'up',
            style: 'position:fixed; bottom:0; left:0; width: 100%; height: 80%; padding:10px 0; border:none;'
        });
    });
</script>
{if $kx.config.app.use_cdn}
<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/api/stat/special/info.js"></script>
{/if}
</html>