<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
    <style>
        .pt-popular-cont li img{
            width: 100%;
            border-radius:10px;
        }
        .pt-popular-cont li .allvisit{
            /*float: right;*/
            padding-left: 20px;
            background: url('https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/images/hot.png') no-repeat;
            background-size: 16px 16px ;
        }
    </style>
</head>
<body>
	<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
		<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/return.png" class="pt-return" onclick="window.history.back();">
		<div class="size18 bold color37">专题列表</div>
        <div><img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxmobileno1/images/ellipsis.png" class="mr5 pt-ellipsis"></div>
        <div class="pt5 pb5 pt-tip">
        </div>
	</div>
    <div class="pt-popular-cont">
        {block method=special.count userid=$userinfo.id name=count}
        {block method="pagination" name="paginate" page=$page limit=$pageSize count=$count maxpage=50 section=3}
        {block method=special.list num=$paginate.limit page=$paginate.current name=list}
        <ul>
            {loop}
            <li>
                <a href="{link=detail specialid=$loop.id}" title="{$loop.intro}">
                    <img src="{$loop.cover}" alt="{$loop.intro}">
                    <span class="fl size16 bold color32 compulsory-row-one" style="width: 80%">{$loop.title}</span>
                    <span class="allvisit">{$loop.num_allvisit}</span>
                </a>
            </li>
            {/loop}
        </ul>
    </div>
    {if $paginate.total > 1}
    <div class="flex-wrp flex-between bg-white ptb15 plr15 mt10">
        {if $paginate.first != $paginate.current}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=index page=$paginate.first}">
                <span class="size14 color2">首页</span>
            </a>
        </div>
        {/if}
        {if $paginate.prev}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=index page=$paginate.prev}">
                <span class="size14 color2">上一页</span>
            </a>
        </div>
        {/if}
        {if $paginate.next}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=index page=$paginate.next}">
                <span class="size14 color2">下一页</span>
            </a>
        </div>
        {/if}
        {if $paginate.last != $paginate.current}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=index page=$paginate.last}">
                <span class="size14 color2">尾页</span>
            </a>
        </div>
        {/if}
    </div>
    {/if}

    <!-- 底部版权 -->
    {include file="/system/footer"}
</body>
</html>