<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/css/global.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<!-- 头部 -->
<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
    <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/return.png" class="pt-return">
    <div class="size18 bold color37">{$author.name}</div>
    <div>
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/ellipsis.png" class="mr5 pt-ellipsis">
    </div>
    <div class="pt5 pb5 pt-tip">
        <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
        <a href="{link=novel.search.index}" class="block color1 text-center pt-tip-item">搜索小说</a>
        <a href="{link=user.mark.index}" class="block color1 text-center pt-tip-item" rel="nofollow">我的书架</a>
        <a href="{link=user.index.index}" class="block color1 text-center pt-tip-item" rel="nofollow">个人中心</a>
    </div>

</div>

<!-- 本书作者 -->
<div class="w100 bg-white lh100 pt-author">
    {block method="novel.list" name=list author=$author.id num=$author.num order='postdate'}
    <div class="flex-wrp mt10 border-b ptb20">
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/static/image/noavatar.gif" class="mr10 pt-author-icon">
        <div class="flex-item flex-wrp flex-cell flex-around">
            <div class="size14 color2">{$author.name}</div>
            <div class="compulsory-row lh140 size12 color4">VIP签约作家</div>
        </div>
    </div>
    <div class="flex-wrp flex-between ptb10 lh100 border-b">
        <div class="w50 lh150 pl10 border-r-d5 mr10">
            <span class="color62 size14 mr15">作品数量</span>
            <span class="size12 color2 pl20">{$author.num}</span>
        </div>
        <div class="lh150">
            <span class="color62 size14 mr15">累计创作</span>
            <span class="size12 color2 pl20">{$list|array_column_sum=@,"data.words"}万字</span>
        </div>
    </div>
    {section loop=$list item=$loop}
    <div class="flex-wrp pt-finish-item" data-id="{$loop.novel.id}" data-pinyin="{$loop.novel.pinyin}">
        <a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
            <img src="{$loop.novel.cover}" class="mr15" alt="{$loop.novel.name}">
        </a>
        <div class="flex-item flex-wrp flex-cell flex-between pt5">
            <a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}">
                <div class="size14 color7">{$loop.novel.name}</div>
            </a>
            <a title="{$loop.category.name}" href="{link=novel.category.list id=$loop.category.id key=$loop.category.key}">
                <div class="size12 color5">{$loop.category.name}</div>
            </a>
            <div class="size12 compulsory-row-one lh130 color4">{$loop.novel.intro|showIntroLine}</div>
            <div class="flex-wrp flex-between">
                <div class="flex-wrp flex-align-center color5 size12">{$loop.last.time|cntime}更新</div>
                <div class="pt-finish-label">{=$loop.data.words}万字</div>
            </div>
        </div>
    </div>
    {/section}
</div>
<!-- 底部版权 -->
{include file="/system/footer"}
<!-- 底部按钮 -->
{include file="/system/footerbutton"}
</body>
</html>