<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
	<title>Document</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/js/flexible.min.js"></script>
    <style>
        select {
            border: none;
            -webkit-appearance: none;
            -webkit-tap-highlight-color: #fff;
            outline: 0;
            padding: 0 .1rem;
        }
        .icon{
            padding-top: 1rem;
            width: 100%;
            height: 69px;
            background-position: center;
            background-repeat: no-repeat;
        }
        .icon.success {
            background-image: url("https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/read_bg_selecd.png");
        }
        .icon.error{
            background-image: url("https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/img_delete.png");
        }
    </style>
</head>
<body>
    <form method="post">
        <div class="w100 vh100">
            <div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
                <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/return.png" class="pt-return">
                <div class="size18 bold color37">{$msgname}{$msgtitle}提示</div>
                <div></div>
            </div>
            <div class="bg-white mt10">
                <div class="icon {$msgtype}"></div>

                <div class="flex-wrp flex-align-center flex-between plr15 ptb15">
                    <h4 class="color2 text-center w100">{$message}</h4>
                </div>
                <div class="flex-wrp flex-align-center flex-between plr15 pb15 border-b">
                    {if $waitsecond}
                    <div class="text-center w100 size12">
                        <span id="second">{$waitsecond}</span>秒后自动跳转,如果浏览器没有自动跳转，请 <a href="javascript:redirect()" id="jumourl" class="color2">点击这里</a>
                    </div>
                    {/if}
                </div>
            </div>
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/js/jquery-3.3.1.js"></script>
    {if $waitsecond}
    <script type = "text/javascript">
        var time = parseInt("{$waitsecond}");
        function redirect() {
            var url = "{$jumpurl}";
            if (url == '#back#') {
                history.back(-1);
            } else if (url == '#close#') {
                window.close();
            } else {
                location.href = url;
            }
        }
        function change() {
            document.getElementById('second').innerHTML = --time;
            if (time == 0) {
                clearInterval(t);
                redirect();
            }
        }
        t = setInterval('change()', 1000);
    </script>
    {/if}
	<script>
		$('.pt-return').click(function(){
			window.history.back();
		})
	</script>
</body>
</html>