<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <title>{$tkd.title|parseTpl}</title>
    <meta name="keywords" content="{$tkd.keywords|parseTpl}">
    <meta name="description" content="{$tkd.description|parseTpl}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/css/global.css"/>
	<script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/js/flexible.min.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
    {block method="pagination" name="paginate" page=$page limit=$pagesize count=$count maxpage=50 section=3}
	<div class="w100  bg-white flex-wrp flex-align-center flex-between lh100 plr15 ptb15">
		<img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/return.png" class="pt-return">
        <a href="/"><div class="size18 bold color37">{$rankname}</div></a>
        <div>
            <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/ruixinm1/images/ellipsis.png" class="mr5 pt-ellipsis">
        </div>
        <div class="pt5 pb5 pt-tip">
            <a href="{link=novel.rank.index}" class="block color1 text-center pt-tip-item" title="{$novel.name}">返回排行</a>
            <a href="{link=index.index}" class="block color1 text-center pt-tip-item" title="{$kx.config.sitename}">前往首页</a>
            <a href="{link=novel.search.index}" class="block color1 text-center pt-tip-item">搜索小说</a>
            <a href="{link=user.mark.index}" class="block color1 text-center pt-tip-item" rel="nofollow">我的书架</a>
            <a href="{link=user.index.index}" class="block color1 text-center pt-tip-item" rel="nofollow">个人中心</a>
        </div>
	</div>

    <!-- 内容 -->
	<div class="pt-popular-cont mt10">
        {section loop=$ranklist item=$loop}
        {if $loop.novel.id}
		<div class="flex-wrp pt-popular-item">
			<a href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}"><img src="{$loop.novel.cover}" class="mr15" alt="{$loop.novel.name}"></a>
			<div class="flex-item flex-wrp flex-cell flex-between pt5" style="max-width: 2.65rem;">
				<div class="flex-wrp flex-between">
                    <div class="size14 ">
                        <a title="{$loop.novel.name}" href="{link=novel.novel.index novelid=$loop.novel.id pinyin=$loop.novel.pinyin}" class="color7">{$loop.novel.name}</a>
                    </div>
					<div class="color2 size14">{$loop.data.mark} <span class="size12">人在追</span></div>
				</div>
				<div class="size12 compulsory-row lh130 color4">{$loop.novel.intro|showIntroLine}</div>
				<div class="flex-wrp flex-between">
					<div class="size12">
                        <a title="{$loop.author.name}" href="{link=author.space.index authorid=$loop.author.id pinyin=$loop.author.pinyin name=$loop.author.name}" class="color5">[ {$loop.author.name} ]</a>
                    </div>
					<div class="pt-popular-label">
                        <a title="{$loop.category.name}" href="{link=novel.category.list id=$loop.category.id key=$loop.category.key}" class="color4">{$loop.category.name}</a>
                    </div>
				</div>
			</div>
		</div>
        {else}
        <div class="flex-wrp pt-popular-item">
            <img src="{$loop.novel.cover}" class="mr15">
            <div class="flex-item flex-wrp flex-cell flex-between pt5">
                <div class="flex-wrp flex-between">
                    <div class="size14 ">
                        <span class="color7">{$loop.novel.name}</span>
                    </div>
                    <div class="color2 size14"><span class="size12">外站书籍</span></div>
                </div>
                <div class="size12 compulsory-row lh130 color4">{$loop.novel.intro|showIntroLine}</div>
                <div class="flex-wrp flex-between">
                    <div class="size12">
                        <span class="color5">[ {$loop.author.name} ]</>
                    </div>
                    <div class="pt-popular-label">
                        <span class="color4">{$loop.category.name}</>
                    </div>
                </div>
            </div>
        </div>
        {/if}
        {/section}
    </div>
    {if $paginate.total > 1}
    <div class="flex-wrp flex-between bg-white ptb15 plr15 mt10">
        {if $paginate.first != $paginate.current}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.rank.list key=$rankkey page=$paginate.first}">
                <span class="size14 color2">首页</span>
            </a>
        </div>
        {/if}
        {if $paginate.prev}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.rank.list key=$rankkey page=$paginate.prev}">
                <span class="size14 color2">上一页</span>
            </a>
        </div>
        {/if}
        {if $paginate.next}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.rank.list key=$rankkey page=$paginate.next}">
                <span class="size14 color2">下一页</span>
            </a>
        </div>
        {/if}
        {if $paginate.last != $paginate.current}
        <div class="flex-wrp flex-around flex-center pt-page4">
            <a href="{link=novel.rank.list key=$rankkey page=$paginate.last}">
                <span class="size14 color2">尾页</span>
            </a>
        </div>
        {/if}
    </div>
    {/if}
    <!-- js -->
    <!-- 底部版权 -->
    {include file="/system/footer"}
    <!-- 底部按钮 -->
    {include file="/system/footerbutton"}
</body>
</html>