<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{$news.title} - {$kx.config.sitename}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/style.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.zhiqiang.name">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<!-- 头部 -->
{include file="system/header"}

<!-- 内容 -->
<div class="pt-content">
    <!-- 面包屑 -->
    <div class="pt-crumb">
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/images/crumb_icon.png" class="pt-crumb-icon">
        <span class="color5"><a title="{$kx.config.sitename}" href="{$kx.config.siteurl}">{$kx.config.sitename}</a> > {$news.title}</span>
    </div>


    <!-- 一楼 -->
    <div class="pt-floor1">
        <div class="pt-list">
            <!-- 我的 -->
            <div class="fr pt-toplist">
                <div class="border-b size18 bold color8 pb10 pt-toplist-title">新闻中心</div>
                <div class="pt-toplist-item">
                    {block method="news.category" name=list}
                    {section loop=$list item=$loop}
                    <a title="{$loop.name}" href="{link=news.list categoryid=$loop.id}" {if $loop.id == $news.category.id}class="color2"{/if}>
                    <span class="mr10">·</span><span>{$loop.name}</span>
                    </a>
                    {/section}
                </div>
            </div>
        </div>
        <!-- 推荐 -->
        <div class="relative pt-rank">
            <!-- 书架title -->
            <div class="pt-privacy-title">
                <span class="color2 size24">{$news.title}</span>
            </div>
            <div class="pt-privacy-desc">
                <span class="mr15">分类：<a title="{$news.category.name}" class="color4" href="{link=news.list categoryid=$news.category.id}">{$news.category.name}</a></span>
                <span class="mr15">用户：{$news.user.name}</span>
                <span>时间：{$news.create_time|date="Y-m-d H:i:s"}</span>
            </div>
            <div class="pt-privacy-cont">
                {$news.content}
            </div>
        </div>
    </div>
    <!-- 广告位 -->
</div>

<!-- 底部版权-->
{include file="/system/footer"}
<!-- js-->
</body>
</html>