<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>新闻中心 - {$kx.config.sitename}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/global.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/css/style.css"/>
    <script src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/js/jquery-3.3.1.js"></script>
    <link rel="shortcut icon" type="image/ico" href="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/favicon.ico" />
    <meta name="author" content="www.ptcms.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <meta name="applicable-device" content="pc">
    <meta http-equiv="mobile-agent" content="format=html5; url={$kx.config.mobileurl}__SELF__">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <link rel="canonical" href="{$kx.config.pcurl}__SELF__" />
</head>
<body>
<!-- 头部 -->
{include file="system/header"}

<!-- 内容 -->
<div class="pt-content">
    <!-- 面包屑 -->
    <div class="pt-crumb">
        <img src="https://cdn.jsdelivr.net/gh/zylx0532/CDN/ptcms/public/template/kxwebno1/images/crumb_icon.png" class="pt-crumb-icon">
        <span class="color5"><a title="{$kx.config.sitename}" href="{$kx.config.siteurl}">{$kx.config.sitename}</a> > 新闻中心</span>
    </div>

    <!-- 一楼 -->
    <div class="pt-floor1">
        <div class="pt-list">
            <!-- 我的 -->
            <div class="fr pt-toplist">
                <div class="border-b size18 bold color8 pb10 pt-toplist-title">新闻中心</div>
                <div class="pt-toplist-item">
                    {block method="news.category" name=list}
                    {section loop=$list item=$loop}
                    <a title="{$loop.name}" href="{link=news.list categoryid=$loop.id}" {if $loop.id == $categoryid}class="color2"{/if}>
                    <span class="mr10">·</span><span>{$loop.name}</span>
                    </a>
                    {/section}
                </div>
            </div>
        </div>
        <!-- 推荐 -->
        <div class="relative pt-rank">
            <div class="news bg-white">
                <ul>
                    {block method="pagination" name="paginate" page=$page limit=$pageSize count=$count maxpage=50 section=3}
                    {block method="news.list" name=list categoryid=$categoryid num=$paginate.limit page=$paginate.current}
                    {if empty($list)}
                    <li class="p15">
                        <span class="fl color0" style="width: 80%">似乎没有数据</span>&nbsp;
                    </li>
                    {else}
                        {loop}
                        <li class="p15">
                            <a href="{link=news.detail newsid=$loop.id}" title="{$loop.title}" target="_blank">
                                <span class="fl compulsory-row-one color6" style="width: 80%">[{$loop.category.name}] {$loop.title}</span>&nbsp;
                                <span class="fr colore9">{$loop.create_time|date="Y-m-d H:i:s"}</span>
                            </a>
                        </li>
                        {/loop}
                    {/if}
                </ul>
            </div>
            {if $paginate.total>1}
            <div class="pt-pages">
                <div class="pt30 color5">
                    {if $paginate.prev}
                    <a href="{link=news.list categoryid=$category.id page=$paginate.prev}"><span><</span></a>
                    {else}
                    <span class="disable"><</span>
                    {/if}
                    {loop=paginate.items}
                    <a href="{link=news.list categoryid=$category.id page=$loop.num}">
                        <span class="{$loop.status|default='','pt-pages-select'}">{$loop.num}</span>
                    </a>
                    {/loop}
                    {if $paginate.next}
                    <a href="{link=news.list categoryid=$category.id page=$paginate.next}"><span>></span></a>
                    {else}
                    <span class="disable">></span>
                    {/if}
                </div>
            </div>
            {/if}
        </div>
    </div>
    <!-- 广告位 -->
</div>

<!-- 底部版权-->
{include file="/system/footer"}
<!-- js-->
</body>
</html>